### ISSUE TITLE
Attempting to send mail from an on-premise installation to external SMTP server fails with "Helo command rejected: need fully-qualified hostname"

### ISSUE THREAD

**Issue by timeggleston** [bitwarden/core#164]
I am running on-premise and attempting to send mail to my external account at ProtonMail. This does not require authentication (because it's delivery, not relay), so I have left those fields blank.

`
globalSettings__mail__replyToEmail=no-reply@<my domain>
globalSettings__mail__smtp__host=mail.protonmail.ch
globalSettings__mail__smtp__username=REPLACE
globalSettings__mail__smtp__password=REPLACE
globalSettings__mail__smtp__ssl=true
globalSettings__mail__smtp__port=25
globalSettings__mail__smtp__useDefaultCredentials=true
`

Trying to verify my email address yields no email and this in the logs:

> 2017-12-12 04:31:13.023 +00:00 [Error] Mail send failed.
System.Net.Mail.SmtpException: Command parameter not implemented. The server response was: 5.5.2 <14dbc77b56a5>: Helo command rejected: need fully-qualified hostname
   at System.Net.Mail.RecipientCommand.CheckResponse(SmtpStatusCode statusCode, String response)
   at System.Net.Mail.RecipientCommand.EndSend(IAsyncResult result, String& response)
   at System.Net.Mail.SendMailAsyncResult.SendToCollectionCompleted(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Mail.SendMailAsyncResult.End(IAsyncResult result)
   at System.Net.Mail.SmtpClient.SendMailCallback(IAsyncResult result)

A normal SMTP transaction with ProtonMail over telnet (a la [this](https://www.port25.com/how-to-check-an-smtp-connection-with-a-manual-telnet-session-2/)) works fine. I've tried sniffing the traffic between BitWarden and the ProtonMail server, but it's encrypted with STARTTLS so I can't see what BW is sending (globalSettings__mail__smtp__ssl doesn't seem to have any effect if the server offers STARTTLS).

Any ideas? Is there a way to crank up the verbosity of the logging, or disable STARTTLS so that I can see what BW is trying to say to the SMTP server?

**Comment by timeggleston** [comment]
More discussion and possible nasty workaround here: https://social.msdn.microsoft.com/Forums/en-US/77f45c5f-76be-400c-a529-a1e49d6d8e62/systemnetmailsmtpclient-fqdn-required?forum=netfxnetcom

**Comment by kspearrin** [comment]
Try changing the username/password settings to empty (remove "REPLACE").

```
globalSettings__mail__smtp__username=
globalSettings__mail__smtp__password=
```

**Comment by timeggleston** [comment]
No change in behaviour unfortunately

**Comment by kspearrin** [comment]
@timeggleston Did you restart after the change?

**Comment by timeggleston** [comment]
@kspearrin Sure did. I've also tried both combinations of useDefaultCredentials

**Comment by kspearrin** [comment]
@timeggleston How can I reproduce this locally? Looks like you are using protonmail?

**Comment by timeggleston** [comment]
@kspearrin Yep you should be able to [sign up](https://protonmail.com/signup) for a free ProtonMail account and then try to send mail to that using mail.protonmail.ch as your SMTP host and port 25, with no authentication.

**Comment by kspearrin** [comment]
I guess I am confused. Why is there no authentication?

**Comment by timeggleston** [comment]
Because I'm not relaying via an intermediate outbound SMTP server, I'm delivering directly to the one that owns my mailbox. Authentication is generally only required if you're relaying, because that protects you against spam (an open relay).

Unauthenticated delivery is how SMTP works -- e.g.  if alice@gmail.com sends mail to bob@protonmail.com, the Gmail mailserver connects to the ProtonMail mailserver via an anonymous connection. I'm just "being Gmail" in this instance.

It's a common setup for people running home labs and the like.

**Comment by kspearrin** [comment]
I tried this locally but am getting the following error:

> A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 185.70.40.101:25

Where are you finding the SMTP server docs for using protonmail this way? I don't find anything with my quick google search.

**Comment by timeggleston** [comment]
For local testing, your ISP is likely blocking port 25 outbound. Make sure you're doing the test on an unfiltered connection like a VPS.

There isn't anything specific to ProtonMail (because it's just standard SMTP) but [here ](https://www.port25.com/how-to-check-an-smtp-connection-with-a-manual-telnet-session-2/)is a good guide on telnet testing. These sorts of tests work fine for me (and I have a Nextcloud instance that sends mail the same way), I only have the problem with Bitwarden. That MSDN discussion I linked upthread is old but perfectly describes the issue symptoms with the .net SMTP client. I'm not sure if that's actually what's going on however, my Docker-fu is too weak to figure out the app.config tracing discussed in there.

**Comment by timeggleston** [comment]
Also see the clientDomain element here: https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/network/network-element-network-settings

Quoting, emphasis mine:

> The clientDomain attribute changes the client domain name used in the initial SMTP protocol request to an SMTP server. **The clientDomain attribute can be set to the fully-qualified domain name of the local machine, rather than the localhost name that is used by default. This provides greater compliance with the SMTP protocol standards**. The default value is the localhost name of the local computer sending the request. The SmtpNetworkElement.ClientDomain property can be used to get the current value of the clientDomain attribute from applicable configuration files.

**Comment by kspearrin** [comment]
I don't think my ISP is blocking the outbound port since I have sent SMTP mail on 25 in the past during development. All of these MS discussions are related to .NET Full Framework on IIS machines, which is not how bitwarden runs. We use .NET Core, which is different. It conforms to the same API specs (.NET Standard, confused yet? 😄), but are different implementations. For example, there is no app.config for us.

**Comment by timeggleston** [comment]
Ah, the frameworkl specifics are out of my wheelhouse :) There's got to be some equivalent configuration though?

For the telnet thing, it's working for me right at this very moment:

> user@host:~$ telnet mailpri.protonmail.ch 25
Trying 185.70.40.101...
Connected to mailpri.protonmail.ch.
Escape character is '^]'.
220-mail6i.protonmail.ch ESMTP Postfix
ehlo example.com
250-mail6i.protonmail.ch
250-PIPELINING
250-SIZE 36480000
250-ETRN
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-8BITMIME
250-DSN
250 SMTPUTF8

There's got to be something going on at your end.

**Comment by kspearrin** [comment]
Not sure. Just tried using an online tool at https://www.smtper.net/ and that doesn't work either.

> Failure sending mail.
> Unable to read data from the transport connection: net_io_connectionclosed.

**Comment by kspearrin** [comment]
Hah. And check out this tool:

https://pingability.com/smtptest.jsp

Attempting to connect via "mail.protonmail.ch" causes:

```
DEBUG: getProvider() returning javax.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle]
DEBUG SMTP: useEhlo true, useAuth false
DEBUG SMTP: trying to connect to host "mail.protonmail.ch", port 25, isSSL false
220-mail7i.protonmail.ch ESMTP Postfix
220 mail7i.protonmail.ch ESMTP Postfix
DEBUG SMTP: connected to host "mail.protonmail.ch", port: 25

EHLO localhost
250-mail7i.protonmail.ch
250-PIPELINING
250-SIZE 36480000
250-ETRN
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-8BITMIME
250-DSN
250 SMTPUTF8
DEBUG SMTP: Found extension "PIPELINING", arg ""
DEBUG SMTP: Found extension "SIZE", arg "36480000"
DEBUG SMTP: Found extension "ETRN", arg ""
DEBUG SMTP: Found extension "STARTTLS", arg ""
DEBUG SMTP: Found extension "ENHANCEDSTATUSCODES", arg ""
DEBUG SMTP: Found extension "8BITMIME", arg ""
DEBUG SMTP: Found extension "DSN", arg ""
DEBUG SMTP: Found extension "SMTPUTF8", arg ""
DEBUG SMTP: use8bit false
MAIL FROM:<smtptester@pingability.com>
250 2.1.0 Ok
RCPT TO:<smtptester@pingability.com>
504 5.5.2 <localhost>: Helo command rejected: need fully-qualified hostname
421 4.7.0 mail7i.protonmail.ch Error: too many errors
DEBUG SMTP: Invalid Addresses
DEBUG SMTP:   smtptester@pingability.com
DEBUG SMTP: Sending failed because of invalid destination addresses
RSET
DEBUG SMTP: MessagingException while sending, THROW: 
javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
	com.sun.mail.smtp.SMTPAddressFailedException: 504 5.5.2 <localhost>: Helo command rejected: need fully-qualified hostname

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1950)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1195)
	at com.rimuhosting.util.email.EmailDetails.sendEmail(EmailDetails.java:579)
	at com.rimuhosting.util.email.EmailDetails.sendEmail(EmailDetails.java:396)
	at org.apache.jsp.smtptest_jsp._jspService(smtptest_jsp.java:268)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:438)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.rimuhosting.util.webrequest.DoNothingFilter.doFilter(DoNothingFilter.java:89)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:617)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
	at org.apache.coyote.ajp.AbstractAjpProcessor.process(AbstractAjpProcessor.java:844)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1521)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1478)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 504 5.5.2 <localhost>: Helo command rejected: need fully-qualified hostname

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1850)
	... 34 more
QUIT
DEBUG SMTP: EOF: [EOF]

Got a relaying denied error (smtptester@pingability.com) 
```

Looks like the same exact error you got before:

> Helo command rejected: need fully-qualified hostname

This time in Java.

**Comment by timeggleston** [comment]
Aha, and yes look at this:

> EHLO localhost

That's not standards-compliant. It should be an FQDN or if one is not available, an IP address. No wonder the ProtonMail server is rejecting it.

I bet the .NET core API is doing the same thing.

**Comment by kspearrin** [comment]
I'm not really sure what we can do. We are just using the APIs available to use here, which I thought was pretty standard. We've never run into this issue before with an SMTP server.

**Comment by timeggleston** [comment]
I just tested the same thing with Gmail (EHLO localhost instead of a proper FQDN) it it accepted the message. Not that Gmail is the arbiter of the way things should work, but I suspect this means I will never get traction despite the .NET API apparently being non-standards compliant. That's disappointing.

How do you run the cloud Bitwarden service in Azure... is it a Web App? I'm interested to see if the same API behaves differently in there vs being containerised.

**Comment by kspearrin** [comment]
Yes, it is an Azure Web App. We don't use SMTP in the version though. We connect through SendGrid's HTTP API.

**Comment by timeggleston** [comment]
Ah okay, that makes sense.

All right, I give up, I'm using SendGrid's SMTP API to work around it, and that works fine. I guess you can close this as an upstream issue?

**Comment by kspearrin** [comment]
@timeggleston Just FYI, if you want to connect to sendgrid through their HTTP API instead of SMTP you can use:

```
globalSettings__mail__sendGridApiKey=SG.xxxxxxxxxxxxxxxxx
```

and just delete all the other `globalSettings__mail__smtp__*` variables.

**Comment by timeggleston** [comment]
@kspearrin Oh that's awesome, thanks! Premium subscription incoming :)
