### ISSUE TITLE
Make sure `mssql` container is running before trying to migratedb

### ISSUE THREAD

**Issue by chamunks** [bitwarden/core#167]
This was a problem that solved itself by just running the command again a minute later but I'm reporting this regardless in case documentation would be improved in some way.

```
./bitwarden.sh updatedb
 _     _ _                         _
| |__ (_) |___      ____ _ _ __ __| | ___ _ __
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2017, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

Docker version 17.09.1-ce, build 19e2cf6
docker-compose version 1.17.0, build ac53b73

1.15.1: Pulling from bitwarden/setup
Digest: sha256:9d4fd9ea670b2ee84eeb19278d6a80bee10f5a50796b3a5f11af1dbdd4b052cf
Status: Image is up to date for bitwarden/setup:1.15.1
Migrating database.

Unhandled Exception: System.Data.SqlClient.SqlException: Login failed for user 'sa'.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Bit.Setup.Program.MigrateDatabase() in /Users/kyle/Projects/bitwarden/core/util/Setup/Program.cs:line 244
   at Bit.Setup.Program.Main(String[] args) in /Users/kyle/Projects/bitwarden/core/util/Setup/Program.cs:line 55
```
I ran ```docker ps -a``` to make sure that none of the containers had crashed for some reason.

```
docker ps -a
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS                                      NAMES
905bca146583        bitwarden/web:1.21.0           "/entrypoint.sh"         4 minutes ago       Up 3 minutes        80/tcp                                     web
53bb3fc37199        bitwarden/mssql:1.15.1         "/entrypoint.sh"         4 minutes ago       Up 3 minutes        1433/tcp                                   mssql
0ec16e604912        bitwarden/icons:1.15.1         "/entrypoint.sh"         4 minutes ago       Up 3 minutes        80/tcp                                     icons
03610e2f7093        bitwarden/api:1.15.1           "/entrypoint.sh"         4 minutes ago       Up 3 minutes        80/tcp                                     api
961d6b6e54c7        bitwarden/attachments:1.15.1   "/entrypoint.sh"         4 minutes ago       Up 3 minutes        80/tcp                                     attachments
9631a0db021f        bitwarden/identity:1.15.1      "/entrypoint.sh"         4 minutes ago       Up 3 minutes        80/tcp                                     identity
63d05b6cb147        bitwarden/nginx:1.15.1         "/entrypoint.sh"         4 minutes ago       Up 3 minutes        0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   nginx
```

Running this again a minute later.
```
./bitwarden.sh updatedb
 _     _ _                         _
| |__ (_) |___      ____ _ _ __ __| | ___ _ __
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2017, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

Docker version 17.09.1-ce, build 19e2cf6
docker-compose version 1.17.0, build ac53b73

1.15.1: Pulling from bitwarden/setup
Digest: sha256:9d4fd9ea670b2ee84eeb19278d6a80bee10f5a50796b3a5f11af1dbdd4b052cf
Status: Image is up to date for bitwarden/setup:1.15.1
Migrating database.
Beginning transaction
Beginning database upgrade
Fetching list of already executed scripts.
The [dbo].[Migration] table could not be found. The database is assumed to be at version 0.
Executing SQL Server script 'Bit.Setup.DbScripts.2017-08-19_00_InitialSetup.sql'
Creating the [dbo].[Migration] table
The [dbo].[Migration] table has been created
Executing SQL Server script 'Bit.Setup.DbScripts.2017-08-22_00_LicenseCheckScripts.sql'
Executing SQL Server script 'Bit.Setup.DbScripts.2017-08-30_00_CollectionWriteOnly.sql'
Executing SQL Server script 'Bit.Setup.DbScripts.2017-09-06_00_CipherDetails.sql'
Executing SQL Server script 'Bit.Setup.DbScripts.2017-09-08_00_OrgUserCounts.sql'
Executing SQL Server script 'Bit.Setup.DbScripts.2017-10-25_00_OrgUserUpdates.sql'
Executing SQL Server script 'Bit.Setup.DbScripts.2017-11-06_00_FamilyPlanAdjustments.sql'
Executing SQL Server script 'Bit.Setup.DbScripts.2017-11-13_00_IndexTuning.sql'
Executing SQL Server script 'Bit.Setup.DbScripts.2017-11-24_00_UpdateProcs.sql'
Upgrade successful
Migration successful.
Database update complete
```

**Comment by kspearrin** [comment]
It's possible that mssql wasn't fully started up/initialized yet and that the database wasn't reachable.

**Comment by chamunks** [comment]
It's very likely the case, I think that there is some way that's documented in ```docker-compose.yml```  that lets you set dependencies for certain parts of the container cluster.  I don't unfortunately have it on hand though.  It might have something to do with health-checks and things of that kind.
[Startup Order](https://docs.docker.com/compose/startup-order/) might help but there may be something else, I haven't built a docker container in a while and I know that every time I skim the docker mailing list emails they have a constant onslaught of new features which I try to keep on top of.

**Comment by kspearrin** [comment]
I ran into this today. It's definitely what I suspected.

**Comment by JorisInsign** [comment]
Hi,

I just ran into this issue. But I can't figure how to make it run...
Here is my ps -a : 
```
$ docker ps -a
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS                   PORTS                                      NAMES
6fb776e6a4d3        bitwarden/attachments:1.16.0   "/entrypoint.sh"         5 minutes ago       Up 3 minutes             80/tcp                                     bitwarden-attachments
dca60e865229        bitwarden/api:1.16.0           "/entrypoint.sh"         5 minutes ago       Up 3 minutes             80/tcp                                     bitwarden-api
7e4030210dc5        bitwarden/mssql:1.16.0         "/entrypoint.sh"         5 minutes ago       Up 13 seconds            1433/tcp                                   bitwarden-mssql
cc4a12d4d2cb        bitwarden/identity:1.16.0      "/entrypoint.sh"         5 minutes ago       Up 5 minutes             80/tcp                                     bitwarden-identity
7abf59f2e5a1        bitwarden/icons:1.16.0         "/entrypoint.sh"         5 minutes ago       Up 3 minutes             80/tcp                                     bitwarden-icons
417c896f1ebe        bitwarden/web:1.22.0           "/entrypoint.sh"         5 minutes ago       Up 5 minutes             80/tcp                                     bitwarden-web
13895097e3e8        bitwarden/nginx:1.16.0         "/entrypoint.sh"         5 minutes ago       Up 2 minutes             0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   bitwarden-nginx
```
My mssql was "restart" with a `docker restart 7e4030210dc5` ... but the error is still here : 
```
$ ./bitwarden.sh updatedb
 _     _ _                         _            
| |__ (_) |___      ____ _ _ __ __| | ___ _ __  
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \ 
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2018, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

Docker version 17.12.0-ce, build c97c6d6
docker-compose version 1.18.0, build 8dd22a9

1.16.0: Pulling from bitwarden/setup
Digest: sha256:edb5dc8a64ff2fc890bc4213574ab67c260b345c3dd259e2fed5549c1f299b05
Status: Image is up to date for bitwarden/setup:1.16.0
Migrating database.

Unhandled Exception: System.Data.SqlClient.SqlException: Login failed for user 'sa'.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Bit.Setup.Program.MigrateDatabase() in /Users/kyle/Projects/bitwarden/core/util/Setup/Program.cs:line 246
   at Bit.Setup.Program.Main(String[] args) in /Users/kyle/Projects/bitwarden/core/util/Setup/Program.cs:line 55
```

I already try to remove all installation (./bitwarden.sh stop && rm -Rf ./btwdata && remove all docker images with Kitematic), but the problem appear again...

I'm on Mac OS High Sierra and trying to test bitwarden at "localhost".

Thanks for your help

**Comment by kspearrin** [comment]
@JorisInsign This is a different issue. You likely need to reinstall again except this time you need to remove the old macOS volume for the database from your previous installation. 

`docker rmi docker_default` i believe is the command you need.

**Comment by kspearrin** [comment]
I added a 7 seconds sleep in the next version, so hopefully that will give enough time for mssql to be available for the migration.
