### ISSUE TITLE
Docker on-premise Bitwarden installation can't connect to MSSQL database

### ISSUE THREAD

**Issue by JimyRyan** [bitwarden/core#195]
I got issues with local installed version of bitwarden on Docker.

- I successfully installed Bitwarden on premise environment by this way: 
```
curl -s -o bitwarden.sh https://raw.githubusercontent.com/bitwarden/core/master/scripts/bitwarden.sh 
sudo chmod u+x bitwarden.sh
./bitwarden.sh install
 ```
- I starting all Bitwarden containers' using the start command:
`./bitwarden.sh start`

- All Bitwarden container's stay in `running` state 
```
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS              PORTS                                              NAMES
2b9671565843        bitwarden/identity:1.16.0       "/entrypoint.sh"         19 minutes ago      Up 19 minutes       80/tcp                                             bitwarden-identity
0fb6122310ae        bitwarden/attachments:1.16.0    "/entrypoint.sh"         19 minutes ago      Up 19 minutes       80/tcp                                             bitwarden-attachments
56c0e2dd45e0        bitwarden/web:1.22.0            "/entrypoint.sh"         19 minutes ago      Up 19 minutes       80/tcp                                             bitwarden-web
b36e96701b80        bitwarden/icons:1.16.0          "/entrypoint.sh"         19 minutes ago      Up 19 minutes       80/tcp                                             bitwarden-icons
686485240e3d        bitwarden/mssql:1.16.0          "/entrypoint.sh"         19 minutes ago      Up 19 minutes       1433/tcp                                           bitwarden-mssql
a0cc27b26849        bitwarden/api:1.16.0            "/entrypoint.sh"         19 minutes ago      Up 19 minutes       80/tcp                                             bitwarden-api
1e6b6a5aa3f4        bitwarden/nginx:1.16.0          "/entrypoint.sh"         19 minutes ago      Up 19 minutes       0.0.0.0:8080->80/tcp, 0.0.0.0:8081->443/tcp      bitwarden-nginx
```

- Bitwarden is up and running! Using my browser (Firefox 58), I visit my Bitwarden local installation at https://localhost:8081, I fill the web form to create a new user account and click on the button "Submit". After 30 seconds, I got the server response "**Errors have occurred. An unhandled server error has occurred.**"
 
- The only use full logs that I have found at this moment is theses from **Bitwarden API container**. Bellow, the entier log: 

```
Hosting environment: Production
Content root path: /app
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.0 POST http://my-host.com/accounts/register application/json;charset=utf-8 2432
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method Bit.Api.Controllers.AccountsController.PostRegister (Api) with arguments (Bit.Core.Models.Api.RegisterRequestModel) - ModelState is Valid
fail: Bit.Api.Utilities.ExceptionHandlerFilterAttribute[0]
      A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server)
System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server)
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__31`1.MoveNext() in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 389
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Bit.Core.Repositories.SqlServer.UserRepository.<GetByEmailAsync>d__3.MoveNext() in /Users/kyle/Projects/bitwarden/core/src/Core/Repositories/SqlServer/UserRepository.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Bit.Core.Identity.UserStore.<FindByEmailAsync>d__6.MoveNext() in /Users/kyle/Projects/bitwarden/core/src/Core/Identity/UserStore.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Bit.Core.Identity.UserStore.<FindByNameAsync>d__8.MoveNext() in /Users/kyle/Projects/bitwarden/core/src/Core/Identity/UserStore.cs:line 73
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Identity.UserValidator`1.<ValidateUserName>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Identity.UserValidator`1.<ValidateAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Identity.UserManager`1.<ValidateUserInternal>d__169.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Identity.UserManager`1.<CreateAsync>d__73.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Identity.UserManager`1.<CreateAsync>d__78.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Bit.Core.Services.UserService.<RegisterUserAsync>d__26.MoveNext() in /Users/kyle/Projects/bitwarden/core/src/Core/Services/Implementations/UserService.cs:line 214
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Bit.Api.Controllers.AccountsController.<PostRegister>d__7.MoveNext() in /Users/kyle/Projects/bitwarden/core/src/Api/Controllers/AccountsController.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()
ClientConnectionId:00000000-0000-0000-0000-000000000000

```

- I'm using Docker version 17.05.0-ce

**Comment by kspearrin** [comment]
Sounds like you forgot to run the last step, `updatedb`.

**Comment by JimyRyan** [comment]
I retry my installation including the `updatedb` command but I always got the same problem :(

Bellow, the logs of execution of `./bitwarden.sh updatedb`:
```
1.16.0: Pulling from bitwarden/setup
Digest: sha256:edb5dc8a64ff2fc890bc4213574ab67c260b345c3dd259e2fed5549c1f299b05
Status: Image is up to date for bitwarden/setup:1.16.0
Migrating database.
Beginning transaction
Beginning database upgrade
Fetching list of already executed scripts.
No new scripts need to be executed - completing.
Migration successful.
Database update complete
```

**Comment by kspearrin** [comment]
According to the log you posted in the first post (if it's still the same error) the API instance is not able to connect to the mssql instance for some reason. I don't know why that would be if they are both up and running. Clearly the setup instance is able to connect to it since it ran the migration. Can you confirm it's still the same error as before?

**Comment by JimyRyan** [comment]
Yes, it's the same error.

**Comment by kspearrin** [comment]
What is the OS of the host machine?

**Comment by JimyRyan** [comment]
Hello, bellow main host informations: 

- **uname -a**
`Linux 3.10.102 x86_64 GNU/Linux synology_bromolow_3615xs 8 CPUs 31.42GiB memory `

- **docker --version**
`Docker version 17.05.0-ce, build 9f07f0e-synology`

- **docker-compose --version**
`docker-compose version 1.14.0, build c7bdf9e`

**Comment by kspearrin** [comment]
Your compose version seems fairly out of date. Try updating that?

**Comment by JimyRyan** [comment]
I can't, it's managed by Synology itself.

It's a possible issue, but I don't have any issues with other linked containers...

**Comment by JimyRyan** [comment]
Hello,

I re-try using the latest docker-compose version (`docker-compose version 1.18.0, build 8dd22a9`), I got the same error :(

**Comment by JimyRyan** [comment]
After long investigation, I found the problem! It's was a firewall issue :(
I discover the Docker not only use only IP range 172.17.x.x. In my case, MSSQL container's IP address using 172.18.x.x IP range or firewall drop all traffic from this IP range.
It's now working!
