### ISSUE TITLE
Upload License isn´t working

### ISSUE THREAD

**Issue by scifire91** [bitwarden/core#200]
Hey,

we just ordered an Enterprise  license and i tried to upload it in our local installation but i got the error:
`Errors have occurred
An unhandled server error has occurred.`

I´ve updated the docker and tried it again but we´re already on the newest version (1.16.0). 

Error log says:
```
2018-01-30 10:57:24.025 +00:00 [Error] Version 3 is not supported.
System.NotSupportedException: Version 3 is not supported.
   at Bit.Core.Models.Business.UserLicense.GetDataBytes(Boolean forHash) in /Users/kyle/Projects/bitwarden/core/src/Core/Models/Business/UserLicense.cs:line 96
   at Bit.Core.Models.Business.UserLicense.VerifySignature(X509Certificate2 certificate) in /Users/kyle/Projects/bitwarden/core/src/Core/Models/Business/UserLicense.cs:line 151
   at Bit.Core.Services.UserService.<SignUpPremiumAsync>d__42.MoveNext() in /Users/kyle/Projects/bitwarden/core/src/Core/Services/Implementations/UserService.cs:line 558
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Bit.Api.Controllers.AccountsController.<PostPremium>d__25.MoveNext() in /Users/kyle/Projects/bitwarden/core/src/Api/Controllers/AccountsController.cs:line 403
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()

```
What did i wrong?

**Comment by scifire91** [comment]
When i use the "Go Premium" link license upload won´t work but if i go through "Create Organization" upload works fine.

Maybe you want to change the how to or is there something wrong in the code...

**Comment by kspearrin** [comment]
Error sounds like you're on an outdated installation. Can you confirm version at https://yourdomain.com/api/version ?

**Comment by scifire91** [comment]
{"Version":"1.16.0","Object":"version"}

**Comment by kspearrin** [comment]
Contact support@bitwarden.com and include your license file as an attachment so we can look at it there.

**Comment by kspearrin** [comment]
This is an org license, not a premium. This is why you get the error.
