### ISSUE TITLE
System.IO.IOException: Permission denied in CertBuilder.cs

### ISSUE THREAD

**Issue by fheuer** [bitwarden/core#239]
When installing this happens:
```(!) Do you want to generate a self-signed SSL certificate? (y/n): y

Unhandled Exception: System.UnauthorizedAccessException: Access to the path '/bitwarden/ssl/self/localhost/' is denied. ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.UnixFileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Bit.Setup.CertBuilder.BuildForInstall() in /Users/kyle/Projects/bitwarden/core/util/Setup/CertBuilder.cs:line 30
   at Bit.Setup.Program.Install() in /Users/kyle/Projects/bitwarden/core/util/Setup/Program.cs:line 87
   at Bit.Setup.Program.Main(String[] args) in /Users/kyle/Projects/bitwarden/core/util/Setup/Program.cs:line 55```

Already created multiple possible directories as root and changed all with 
`chmod -R 777`. Still unresolved and no workaround. Trying to install as different user next.

**Comment by kspearrin** [comment]
you need to run ./bitwarden.sh with sudo.

**Comment by fheuer** [comment]
That reply was quick but not the solution

**Comment by fheuer** [comment]
update: Execution as different user with sudo rights is not working

**Comment by kspearrin** [comment]
What's the OS?

**Comment by fheuer** [comment]
OS is CentOS Linux 7 (3.10.0)

**Comment by fheuer** [comment]
Cause: wrong Docker version
Fix: reinstall Docker CE from repo
