### ISSUE TITLE
mssql Fails on Win10

### ISSUE THREAD

**Issue by cbrompton** [bitwarden/core#249]
Fresh install on Windows 10 v1709
Docker 18.03.0
I think its related to [this](https://github.com/Microsoft/mssql-docker/issues/136)
if I modify the volume in the docker compose to not mount from the host, the issue goes away like was mentioned [here](https://github.com/Microsoft/mssql-docker/issues/136#issuecomment-319970270)

It looks like this was fixed in a different tagged version of the mssql docker image. Not sure how to get around this since the above workaround obviously eliminates db persistence. 

**Results from Updatedb**
 .\bitwarden.ps1 -updatedb
```
 _     _ _                         _
| |__ (_) |___      ____ _ _ __ __| | ___ _ __
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2018, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

Docker version 18.03.0-ce, build 0520e24
docker-compose version 1.20.1, build 5d8c71b2

1.17.2: Pulling from bitwarden/setup
Digest: sha256:cf55e0288b6392ee9c35022089396c3c561773ddc963945f1afea8fce359757f
Status: Image is up to date for bitwarden/setup:1.17.2
Migrating database.

Unhandled Exception: System.Data.SqlClient.SqlException: A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 0 - Unknown error 203) ---> System.ComponentModel.Win32Exception: Unknown error 203
   --- End of inner exception stack trace ---
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Bit.Setup.Program.MigrateDatabase() in /Users/kyle/Projects/bitwarden/core/util/Setup/Program.cs:line 246
   at Bit.Setup.Program.Main(String[] args) in /Users/kyle/Projects/bitwarden/core/util/Setup/Program.cs:line 55
Database update complete
```
**Logs from mssql Container**
```
2018-03-30 16:27:02.14 Server      Microsoft SQL Server 2017 (RTM-CU4) (KB4056498) - 14.0.3022.28 (X64)
        Feb  9 2018 19:39:09
        Copyright (C) 2017 Microsoft Corporation
        Express Edition (64-bit) on Linux (Ubuntu 16.04.3 LTS)
2018-03-30 16:27:02.14 Server      UTC adjustment: 0:00
2018-03-30 16:27:02.14 Server      (c) Microsoft Corporation.
2018-03-30 16:27:02.14 Server      All rights reserved.
2018-03-30 16:27:02.14 Server      Server process ID is 4120.
2018-03-30 16:27:02.14 Server      Logging SQL Server messages in file '/var/opt/mssql/log/errorlog'.
2018-03-30 16:27:02.15 Server      Registry startup parameters:
         -d /var/opt/mssql/data/master.mdf
         -l /var/opt/mssql/data/mastlog.ldf
         -e /var/opt/mssql/log/errorlog
2018-03-30 16:27:02.17 Server      SQL Server detected 1 sockets with 3 cores per socket and 3 logical processors per socket, 3 total logical processors; using 3 logical processors based on SQL Server licensing. This is an informational message; no user action is required.
2018-03-30 16:27:02.17 Server      SQL Server is starting at normal priority base (=7). This is an informational message only. No user action is required.
2018-03-30 16:27:02.17 Server      Detected 3143 MB of RAM. This is an informational message; no user action is required.
2018-03-30 16:27:02.17 Server      Using conventional memory in the memory manager.
2018-03-30 16:27:02.39 Server      Buffer pool extension is already disabled. No action is necessary.
2018-03-30 16:27:02.52 Server      InitializeExternalUserGroupSid failed. Implied authentication will be disabled.
2018-03-30 16:27:02.53 Server      Implied authentication manager initialization failed. Implied authentication will be disabled.
2018-03-30 16:27:02.53 Server      Successfully initialized the TLS configuration. Allowed TLS protocol versions are ['1.0 1.1 1.2']. Allowed TLS ciphers are ['ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-ECDSA-AES128-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:!DHE-RSA-AES256-GCM-SHA384:!DHE-RSA-AES128-GCM-SHA256:!DHE-RSA-AES256-SHA:!DHE-RSA-AES128-SHA'].
2018-03-30 16:27:02.58 Server      The maximum number of dedicated administrator connections for this instance is '1'
2018-03-30 16:27:02.58 Server      Node configuration: node 0: CPU mask: 0x0000000000000007:0 Active CPU mask: 0x0000000000000007:0. This message provides a description of the NUMA configuration for this computer. This is an informational message only. No user action is required.
2018-03-30 16:27:02.59 Server      Using dynamic lock allocation.  Initial allocation of 2500 Lock blocks and 5000 Lock Owner blocks per node.  This is an informational message only.  No user action is required.
2018-03-30 16:27:02.59 Server      In-Memory OLTP initialized on lowend machine.
2018-03-30 16:27:02.73 Server      Database Instant File Initialization: enabled. For security and performance considerations see the topic 'Database Instant File Initialization' in SQL Server Books Online. This is an informational message only. No user action is required.
2018-03-30 16:27:02.74 Server      Query Store settings initialized with enabled = 1,
2018-03-30 16:27:02.74 Server      Software Usage Metrics is disabled.
2018-03-30 16:27:02.75 spid7s      Starting up database 'master'.
2018-03-30 16:27:03.23 spid7s      10 transactions rolled forward in database 'master' (1:0). This is an informational message only. No user action is required.
2018-03-30 16:27:03.24 spid7s      0 transactions rolled back in database 'master' (1:0). This is an informational message only. No user action is required.
2018-03-30 16:27:03.50 spid7s      SQL Server Audit is starting the audits. This is an informational message. No user action is required.
2018-03-30 16:27:03.51 spid7s      SQL Server Audit has started the audits. This is an informational message. No user action is required.
2018-03-30 16:27:03.52 spid7s      Error: 17053, Severity: 16, State: 1.
2018-03-30 16:27:03.52 spid7s      /var/opt/mssql/data/mastlog.ldf: Operating system error 31(A device attached to the system is not functioning.) encountered.
2018-03-30 16:27:04.58 spid7s      Error: 9002, Severity: 17, State: 0.
2018-03-30 16:27:04.58 spid7s      The transaction log for database 'master' is full due to 'NOTHING'.
2018-03-30 16:27:04.59 spid7s      Error: 25710, Severity: 16, State: 1.
2018-03-30 16:27:04.59 spid7s      Event session "id:65536" failed to start. Refer to previous errors in the current session to identify the cause, and correct any associated problems.
2018-03-30 16:27:04.60 spid7s      Error: 25709, Severity: 16, State: 1.
2018-03-30 16:27:04.60 spid7s      One or more event sessions failed to start. Refer to previous errors in the current session to identify the cause, and correct any associated problems.
2018-03-30 16:27:04.62 spid7s      SQL Trace ID 1 was started by login "sa".
2018-03-30 16:27:04.76 spid19s     A self-generated certificate was successfully loaded for encryption.
2018-03-30 16:27:04.77 spid19s     Server is listening on [ 'any' <ipv4> 1433].
2018-03-30 16:27:04.78 spid19s     Dedicated administrator connection support was not started because it is disabled on this edition of SQL Server. If you want to use a dedicated administrator connection, restart SQL Server using the trace flag 7806. This is an informational message only. No user action is required.
2018-03-30 16:27:04.80 spid19s     SQL Server is now ready for client connections. This is an informational message; no user action is required.
2018-03-30 16:27:05.72 spid7s      Error: 9002, Severity: 17, State: 0.
2018-03-30 16:27:05.72 spid7s      The transaction log for database 'master' is full due to 'NOTHING'.
2018-03-30 16:27:05.73 spid7s      SQL Trace was stopped due to server shutdown. Trace ID = '1'. This is an informational message only; no user action is required.
```

**Comment by kspearrin** [comment]
Yea, unfortunately the latest mssql builds seem to have various issues on windows 10. I am not sure why.

Could you try editing `bwdata/docker/docker-compose.yml` and setting the mssql instance to version 1.16.0? Then restart. That version is on CU2, which was known to work fine on W10.

**Comment by staff0rd** [comment]
For the record I tried to mount a different volume and restore a db from it just in case this was related to startup/master dbs, but got the same error;
```
1> restore database zapmoney from disk ='/data/zapmoney.1804.bak' with move 'zapmoney' to '/data/zapmoney.mdf', move 'zapmoney_log' to '/data/zapmoney_log.ldf'
2> go
Msg 5149, Level 16, State 3, Server mssql, Line 1
MODIFY FILE encountered operating system error 31(A device attached to the system is not functioning.) while attempting to expand the physical file '/data/zapmoney.mdf'.
Msg 3013, Level 16, State 1, Server mssql, Line 1
RESTORE DATABASE is terminating abnormally.
```

**Comment by kspearrin** [comment]
This is being tracked on MSSQL's issue tracker: https://github.com/Microsoft/mssql-docker/issues/180

Please feel free to post your requests there too.

**Comment by SQLGeordie** [comment]
I don't think this is just a latest mssql build issue. I am getting the same issue when trying to mount a drive using the microsoft/mssql-server-linux:2017-GA version.....

docker version:  18.03.0-ce

**Comment by kspearrin** [comment]
Yea, I think it's something to do with the latest docker versions. It used to work.

**Comment by shartge** [comment]
This is very strange.

I got a test-setup working on Debian Sid with docker-ce_18.03.0~ce-0~debian two weeks ago (precisely the 30.03.2018) without problems.

Then two days ago I replicated that setup on a different system with the same docker-ce version and ran into the problems discussed here.

**Comment by kspearrin** [comment]
Simple reproduction to remove any other potential environment issues is mentioned here: https://github.com/Microsoft/mssql-docker/issues/180#issuecomment-377602173

**Comment by kspearrin** [comment]
@SQLGeordie Could you post your results on the MSSQL docker issue linked above? Also, you could try using a docker volume instead.

**Comment by shartge** [comment]
I found my problem with mssql-linux.

The filesystem .../bitwarden/bwdata resides on was missing some ext4 features:

Non-Working:
`Filesystem features:      has_journal ext_attr dir_index filetype needs_recovery meta_bg sparse_super`

Working:
`Filesystem features:      has_journal dir_index filetype needs_recovery meta_bg extent sparse_super large_file uninit_bg`

I guess the missing "large_file" feature is causing this.

Morale of my story: Don't use an improperly upgraded filesystem but make a new one to be extra sure everything is supported.

**Comment by kspearrin** [comment]
Should be fixed now.
