### ISSUE TITLE
Mssql fails to open database 'vault'

### ISSUE THREAD

**Issue by evertvp** [bitwarden/core#269]
The relevant logs:
```
2018-04-23 11:55:35.27 Server      Microsoft SQL Server 2017 (RTM-CU5) (KB4092643) - 14.0.3023.8 (X64)
        Mar  2 2018 18:24:44                                                                                                                              
        Copyright (C) 2017 Microsoft Corporation                        
        Express Edition (64-bit) on Linux (Ubuntu 16.04.4 LTS)                                                                                                
2018-04-23 11:55:35.27 Server      UTC adjustment: 0:00                
2018-04-23 11:55:35.28 Server      (c) Microsoft Corporation.                                                                                                                         2018-04-23 11:55:35.28 Server      All rights reserved.
2018-04-23 11:55:35.28 Server      Server process ID is 4120.            
2018-04-23 11:55:35.28 Server      Logging SQL Server messages in file '/var/opt/mssql/log/errorlog'.                                                
2018-04-23 11:55:35.28 Server      Registry startup parameters:          
         -d /var/opt/mssql/data/master.mdf                                                                                                           
         -l /var/opt/mssql/data/mastlog.ldf                              
         -e /var/opt/mssql/log/errorlog                                                                                                              
2018-04-23 11:55:35.29 Server      SQL Server detected 4 sockets with 1 cores per socket and 1 logical processors per socket, 4 total logical processors; using 1 logical processors b
ased on SQL Server licensing. This is an informational message; no user action is required.                                                          
2018-04-23 11:55:35.29 Server      SQL Server is starting at normal priority base (=7). This is an informational message only. No user action is required.
2018-04-23 11:55:35.30 Server      Detected 3164 MB of RAM. This is an informational message; no user action is required.                            
2018-04-23 11:55:35.30 Server      Using conventional memory in the memory manager.
2018-04-23 11:55:35.76 Server      Buffer pool extension is already disabled. No action is necessary.
2018-04-23 11:55:36.06 Server      InitializeExternalUserGroupSid failed. Implied authentication will be disabled.
2018-04-23 11:55:36.06 Server      Implied authentication manager initialization failed. Implied authentication will be disabled.
2018-04-23 11:55:36.07 Server      Successfully initialized the TLS configuration. Allowed TLS protocol versions are ['1.0 1.1 1.2']. Allowed TLS ciphers are ['ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-ECDSA-AES128-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:!DHE-RSA-AES256-GCM-SHA384:!DHE-RSA-AES128-GCM-SHA256:!DHE-RSA-AES256-SHA:!DHE-RSA-AES128-SHA'].
2018-04-23 11:55:36.14 Server      The maximum number of dedicated administrator connections for this instance is '1'
2018-04-23 11:55:36.13 Server      Node configuration: node 0: CPU mask: 0x0000000000000001:0 Active CPU mask: 0x0000000000000001:0. This message provides a description of the NUMA configuration for this computer. This is an informational message only. No user action is required.
2018-04-23 11:55:36.15 Server      Using dynamic lock allocation.  Initial allocation of 2500 Lock blocks and 5000 Lock Owner blocks per node.  This is an informational message only.  No user action is required.
2018-04-23 11:55:36.17 Server      In-Memory OLTP initialized on lowend machine.
2018-04-23 11:55:36.41 Server      Database Instant File Initialization: enabled. For security and performance considerations see the topic 'Database Instant File Initialization' in SQL Server Books Online. This is an informational message only. No user action is required.
2018-04-23 11:55:36.42 Server      Query Store settings initialized with enabled = 1,
2018-04-23 11:55:36.44 spid6s      Starting up database 'master'.
2018-04-23 11:55:36.47 Server      Software Usage Metrics is disabled.
2018-04-23 11:55:37.25 spid6s      150 transactions rolled forward in database 'master' (1:0). This is an informational message only. No user action is required.
2018-04-23 11:55:37.27 spid6s      0 transactions rolled back in database 'master' (1:0). This is an informational message only. No user action is required.
2018-04-23 11:55:37.27 spid6s      Recovery is writing a checkpoint in database 'master' (1). This is an informational message only. No user action is required.
2018-04-23 11:55:37.60 spid6s      Service Master Key could not be decrypted using one of its encryptions. See sys.key_encryptions for details.
2018-04-23 11:55:37.61 spid6s      An error occurred during Service Master Key initialization. SQLErrorCode=33095, State=8, LastOsError=0.
2018-04-23 11:55:37.88 spid6s      SQL Server Audit is starting the audits. This is an informational message. No user action is required.
2018-04-23 11:55:37.89 spid6s      SQL Server Audit has started the audits. This is an informational message. No user action is required.
2018-04-23 11:55:38.32 spid6s      SQL Trace ID 1 was started by login "sa".
2018-04-23 11:55:38.33 spid6s      Server name is '2f2f30bd1311'. This is an informational message only. No user action is required.
2018-04-23 11:55:38.38 spid21s     Always On: The availability replica manager is starting. This is an informational message only. No user action is required.
2018-04-23 11:55:38.39 spid21s     Always On: The availability replica manager is waiting for the instance of SQL Server to allow client connections. This is an informational message only. No user action is required.
2018-04-23 11:55:38.39 spid9s      Starting up database 'mssqlsystemresource'.
2018-04-23 11:55:38.41 spid6s      Starting up database 'msdb'.
2018-04-23 11:55:38.42 spid9s      The resource database build version is 14.00.3023. This is an informational message only. No user action is required.
2018-04-23 11:55:38.50 spid9s      Starting up database 'model'.
2018-04-23 11:55:39.77 spid18s     A self-generated certificate was successfully loaded for encryption.
2018-04-23 11:55:39.80 spid18s     Server is listening on [ 'any' <ipv4> 1433].
2018-04-23 11:55:39.82 spid18s     Dedicated administrator connection support was not started because it is disabled on this edition of SQL Server. If you want to use a dedicated administrator connection, restart SQL Server using the trace flag 7806. This is an informational message only. No user action is required.
2018-04-23 11:55:39.87 spid18s     SQL Server is now ready for client connections. This is an informational message; no user action is required.
2018-04-23 11:55:39.96 spid6s      2 transactions rolled forward in database 'msdb' (4:0). This is an informational message only. No user action is required.
2018-04-23 11:55:40.00 spid9s      Polybase feature disabled.
2018-04-23 11:55:40.00 spid9s      Clearing tempdb database.
2018-04-23 11:55:40.00 spid6s      0 transactions rolled back in database 'msdb' (4:0). This is an informational message only. No user action is required.
2018-04-23 11:55:40.02 spid6s      Recovery is writing a checkpoint in database 'msdb' (4). This is an informational message only. No user action is required.
2018-04-23 11:55:42.34 spid9s      Starting up database 'tempdb'.
2018-04-23 11:55:42.93 spid21s     The Service Broker endpoint is in disabled or stopped state.
2018-04-23 11:55:42.94 spid21s     The Database Mirroring endpoint is in disabled or stopped state.
2018-04-23 11:55:42.96 spid21s     Service Broker manager has started.
2018-04-23 11:55:43.05 spid6s      Recovery is complete. This is an informational message only. No user action is required.
2018-04-23 11:55:43.90 spid51      Attempting to load library 'xpsqlbot.dll' into memory. This is an informational message only. No user action is required.
2018-04-23 11:55:43.92 spid51      Using 'xpsqlbot.dll' version '2017.140.3023' to execute extended stored procedure 'xp_qv'. This is an informational message only; no user action is required.
2018-04-23 11:55:44.11 spid51      Attempting to load library 'xpstar.dll' into memory. This is an informational message only. No user action is required.
2018-04-23 11:55:44.23 spid51      Using 'xpstar.dll' version '2017.140.3023' to execute extended stored procedure 'xp_sqlagent_notify'. This is an informational message only; no user action is required.
2018-04-23 11:56:36.12 spid70      Starting up database 'vault'.
2018-04-23 11:56:36.55 spid70      Parallel redo is started for database 'vault' with worker pool size [1].
2018-04-23 11:56:36.60 spid70      Parallel redo is shutdown for database 'vault' with worker pool size [1].
2018-04-23 12:00:04.38 spid53      Starting up database 'vault'.
2018-04-23 12:00:05.00 spid53      Parallel redo is started for database 'vault' with worker pool size [1].
2018-04-23 12:00:05.07 spid53      Parallel redo is shutdown for database 'vault' with worker pool size [1].
2018-04-23 12:00:40.65 spid53      Using 'dbghelp.dll' version '4.0.5'
2018-04-23 12:27:24.13 spid53      Error: 19099, Severity: 16, State: 1.
2018-04-23 12:27:24.13 spid53      Trace ID '1' was stopped because of an error. Cause: 0x80070002(The system cannot find the file specified.). Restart the trace after correcting the problem.
2018-04-23 12:30:03.46 spid54      Starting up database 'vault'.
2018-04-23 12:30:03.56 spid54      Error: 17204, Severity: 16, State: 1.
2018-04-23 12:30:03.56 spid54      FCB::Open failed: Could not open file /var/opt/mssql/data/vault.mdf for file number 1.  OS error: 5(Access is denied.).
2018-04-23 12:30:03.66 spid54      Error: 17204, Severity: 16, State: 1.
2018-04-23 12:30:03.66 spid54      FCB::Open failed: Could not open file /var/opt/mssql/data/vault_log.ldf for file number 2.  OS error: 5(Access is denied.).
2018-04-23 12:30:03.67 spid54      Error: 5105, Severity: 16, State: 1.
2018-04-23 12:30:03.67 spid54      A file activation error occurred. The physical file name '/var/opt/mssql/data/vault_log.ldf' may be incorrect. Diagnose and correct additional errors, and retry the operation.
2018-04-23 12:30:03.67 Logon       Error: 18456, Severity: 14, State: 38.
2018-04-23 12:30:03.67 Logon       Login failed for user 'sa'. Reason: Failed to open the explicitly specified database 'vault'. [CLIENT: 172.18.0.6]
2018-04-23 13:10:14.47 Logon       Error: 18456, Severity: 14, State: 38.
2018-04-23 13:10:14.47 Logon       Login failed for user 'sa'. Reason: Failed to open the explicitly specified database 'vault'. [CLIENT: 172.18.0.7]
2018-04-23 13:12:06.49 Logon       Error: 18456, Severity: 14, State: 38.
2018-04-23 13:12:06.49 Logon       Login failed for user 'sa'. Reason: Failed to open the explicitly specified database 'vault'. [CLIENT: 172.18.0.7]
2018-04-23 13:15:15.26 Logon       Error: 18456, Severity: 14, State: 38.
2018-04-23 13:15:15.26 Logon       Login failed for user 'sa'. Reason: Failed to open the explicitly specified database 'vault'. [CLIENT: 172.18.0.7]
2018-04-23 13:20:15.64 Logon       Error: 18456, Severity: 14, State: 38.
2018-04-23 13:20:15.64 Logon       Login failed for user 'sa'. Reason: Failed to open the explicitly specified database 'vault'. [CLIENT: 172.18.0.7]
2018-04-23 13:22:06.94 Logon       Error: 18456, Severity: 14, State: 38.
2018-04-23 13:22:06.94 Logon       Login failed for user 'sa'. Reason: Failed to open the explicitly specified database 'vault'. [CLIENT: 172.18.0.7]
```

When this happens a `./bitwarden.sh stop && ./bitwarden.sh start` fixes the issue, but only for a while. The `vault.mdf` and `vault_log.mdf` files exist in `bwdata/mssql/data` directory and have 0640 permissions. I've also done an `fsck` on the filesystem, which didn't turn up any errors. But as far as I can tell it's not actually a problem with the files since it does work for a while after a restart. I am on the latest version (1.19.0).

**Comment by evertvp** [comment]
It seems to happen between a half hour and an hour after startup (every time).

**Comment by kspearrin** [comment]
Honestly I am not sure. I've never seen this happen before. Is there something that is modifying file permissions on the host machine? Is `0640` what the file permissions are before AND after the issue?

**Comment by evertvp** [comment]
It seems like it's related to the recent 1.18 update. I've tried reinstalling under a different user and copying the bwdata folder. Since then, the problem has not occurred.

**Comment by kspearrin** [comment]
So is this now resolved?

**Comment by evertvp** [comment]
I guess it is yeah, but I still don't get why it happened in the first place though.

**Comment by enoch85** [comment]
@kspearrin 

I was googling and came here as I'm also seeing this issue:

```
root@ubuntu-3cpu-3gb-uk-lon1:/home/bitwarden# docker logs bitwarden-mssql 
2020-08-14 21:06:53.72 Server      The licensing PID was successfully processed. The new edition is [Express Edition].
2020-08-14 21:06:54.07 Server      Microsoft SQL Server 2017 (RTM-CU18) (KB4527377) - 14.0.3257.3 (X64) 
	Nov 16 2019 01:14:50 
	Copyright (C) 2017 Microsoft Corporation
	Express Edition (64-bit) on Linux (Ubuntu 16.04.6 LTS)
2020-08-14 21:06:54.08 Server      UTC adjustment: 0:00
2020-08-14 21:06:54.08 Server      (c) Microsoft Corporation.
2020-08-14 21:06:54.08 Server      All rights reserved.
2020-08-14 21:06:54.08 Server      Server process ID is 28.
2020-08-14 21:06:54.08 Server      Logging SQL Server messages in file '/var/opt/mssql/log/errorlog'.
2020-08-14 21:06:54.08 Server      Registry startup parameters: 
	 -d /var/opt/mssql/data/master.mdf
	 -l /var/opt/mssql/data/mastlog.ldf
	 -e /var/opt/mssql/log/errorlog
2020-08-14 21:06:54.08 Server      SQL Server detected 1 sockets with 3 cores per socket and 3 logical processors per socket, 3 total logical processors; using 3 logical processors based on SQL Server licensing. This is an informational message; no user action is required.
2020-08-14 21:06:54.08 Server      SQL Server is starting at normal priority base (=7). This is an informational message only. No user action is required.
2020-08-14 21:06:54.09 Server      Detected 2394 MB of RAM. This is an informational message; no user action is required.
2020-08-14 21:06:54.09 Server      Using conventional memory in the memory manager.
2020-08-14 21:06:54.27 Server      Buffer pool extension is already disabled. No action is necessary. 
2020-08-14 21:06:54.43 Server      InitializeExternalUserGroupSid failed. Implied authentication will be disabled.
2020-08-14 21:06:54.43 Server      Implied authentication manager initialization failed. Implied authentication will be disabled.
2020-08-14 21:06:54.44 Server      Successfully initialized the TLS configuration. Allowed TLS protocol versions are ['1.0 1.1 1.2']. Allowed TLS ciphers are ['ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-ECDSA-AES128-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:!DHE-RSA-AES256-GCM-SHA384:!DHE-RSA-AES128-GCM-SHA256:!DHE-RSA-AES256-SHA:!DHE-RSA-AES128-SHA'].
2020-08-14 21:06:54.48 Server      The maximum number of dedicated administrator connections for this instance is '1'
2020-08-14 21:06:54.48 Server      Node configuration: node 0: CPU mask: 0x0000000000000007:0 Active CPU mask: 0x0000000000000007:0. This message provides a description of the NUMA configuration for this computer. This is an informational message only. No user action is required.
2020-08-14 21:06:54.50 Server      Using dynamic lock allocation.  Initial allocation of 2500 Lock blocks and 5000 Lock Owner blocks per node.  This is an informational message only.  No user action is required.
2020-08-14 21:06:54.50 Server      In-Memory OLTP initialized on lowend machine.
2020-08-14 21:06:54.57 Server      Database Instant File Initialization: enabled. For security and performance considerations see the topic 'Database Instant File Initialization' in SQL Server Books Online. This is an informational message only. No user action is required.
ForceFlush is enabled for this instance. 
2020-08-14 21:06:54.57 Server      Query Store settings initialized with enabled = 1, 
2020-08-14 21:06:54.58 spid6s      Starting up database 'master'.
2020-08-14 21:06:54.59 Server      Software Usage Metrics is disabled.
ForceFlush feature is enabled for log durability.
2020-08-14 21:06:54.85 spid6s      Service Master Key could not be decrypted using one of its encryptions. See sys.key_encryptions for details.
2020-08-14 21:06:54.85 spid6s      An error occurred during Service Master Key initialization. SQLErrorCode=33095, State=8, LastOsError=0.
2020-08-14 21:06:54.91 spid6s      SQL Server Audit is starting the audits. This is an informational message. No user action is required.
2020-08-14 21:06:54.92 spid6s      SQL Server Audit has started the audits. This is an informational message. No user action is required.
2020-08-14 21:06:54.99 spid6s      SQL Trace ID 1 was started by login "sa".
2020-08-14 21:06:55.00 spid6s      Server name is '994abbe1e0e8'. This is an informational message only. No user action is required.
2020-08-14 21:06:55.02 spid19s     Always On: The availability replica manager is starting. This is an informational message only. No user action is required.
2020-08-14 21:06:55.02 spid6s      Starting up database 'msdb'.
2020-08-14 21:06:55.03 spid9s      Starting up database 'mssqlsystemresource'.
2020-08-14 21:06:55.03 spid19s     Always On: The availability replica manager is waiting for the instance of SQL Server to allow client connections. This is an informational message only. No user action is required.
2020-08-14 21:06:55.04 spid9s      The resource database build version is 14.00.3257. This is an informational message only. No user action is required.
2020-08-14 21:06:55.09 spid9s      Starting up database 'model'.
2020-08-14 21:06:55.33 spid18s     A self-generated certificate was successfully loaded for encryption.
2020-08-14 21:06:55.34 spid18s     Server is listening on [ 'any' <ipv6> 1433].
2020-08-14 21:06:55.34 spid18s     Server is listening on [ 'any' <ipv4> 1433].
2020-08-14 21:06:55.35 spid18s     Dedicated administrator connection support was not started because it is disabled on this edition of SQL Server. If you want to use a dedicated administrator connection, restart SQL Server using the trace flag 7806. This is an informational message only. No user action is required.
2020-08-14 21:06:55.35 spid18s     SQL Server is now ready for client connections. This is an informational message; no user action is required.
2020-08-14 21:06:55.35 spid9s      Polybase feature disabled.
2020-08-14 21:06:55.35 spid9s      Clearing tempdb database.
2020-08-14 21:06:55.79 spid9s      Starting up database 'tempdb'.
2020-08-14 21:06:56.02 spid23s     The Service Broker endpoint is in disabled or stopped state.
2020-08-14 21:06:56.03 spid23s     The Database Mirroring endpoint is in disabled or stopped state.
2020-08-14 21:06:56.04 spid23s     Service Broker manager has started.
2020-08-14 21:06:56.05 spid6s      Recovery is complete. This is an informational message only. No user action is required.
2020-08-14 21:07:12.26 Logon       Error: 18456, Severity: 14, State: 8.
2020-08-14 21:07:12.26 Logon       Login failed for user 'sa'. Reason: Password did not match that for the login provided. [CLIENT: 172.20.0.10]
2020-08-14 21:07:17.38 Logon       Error: 18456, Severity: 14, State: 8.
2020-08-14 21:07:17.38 Logon       Login failed for user 'sa'. Reason: Password did not match that for the login provided. [CLIENT: 172.20.0.2]
2020-08-14 21:07:32.32 Logon       Error: 18456, Severity: 14, State: 8.
2020-08-14 21:07:32.32 Logon       Login failed for user 'sa'. Reason: Password did not match that for the login provided. [CLIENT: 172.20.0.10]
2020-08-14 21:07:47.51 Logon       Error: 18456, Severity: 14, State: 8.
2020-08-14 21:07:47.51 Logon       Login failed for user 'sa'. Reason: Password did not match that for the login provided. [CLIENT: 172.20.0.2]
2020-08-14 21:07:52.35 Logon       Error: 18456, Severity: 14, State: 8.
2020-08-14 21:07:52.35 Logon       Login failed for user 'sa'. Reason: Password did not match that for the login provided. [CLIENT: 172.20.0.10]
```
```
root@ubuntu-3cpu-3gb-uk-lon1:/home/bitwarden# sudo -u bitwarden ./bitwarden.sh updatedb
 _     _ _                         _            
| |__ (_) |___      ____ _ _ __ __| | ___ _ __  
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \ 
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2020, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

Docker version 19.03.12, build 48a66213fe
docker-compose version 1.25.0, build unknown

1.36.1: Pulling from bitwarden/setup
Digest: sha256:5b2c43b46c03da54aecc6d19098b0574b5fb205f0cd3046019725925cadfdf29
Status: Image is up to date for bitwarden/setup:1.36.1
docker.io/bitwarden/setup:1.36.1

Migrating database.
Unhandled exception. System.Data.SqlClient.SqlException (0x80131904): Login failed for user 'sa'.
   at Bit.Setup.Program.MigrateDatabase(Int32 attempt) in /home/runner/work/server/server/util/Setup/Program.cs:line 193
   at Bit.Setup.Program.Update() in /home/runner/work/server/server/util/Setup/Program.cs:line 140
   at Bit.Setup.Program.Main(String[] args) in /home/runner/work/server/server/util/Setup/Program.cs:line 65
ClientConnectionId:0e2505a9-93b3-419b-b625-042a2aefc5a4
Error Number:18456,State:1,Class:14
```
Please advice.
