### ISSUE TITLE
Bitwarden fails to start on CentOS 7

### ISSUE THREAD

**Issue by waza-ari** [bitwarden/core#274]
I just installed Bitwarden on a blank CentOS 7 server, but it fails to start with the following traceback:

```
[root@centos-2gb-bitwarden bitwarden]# ./bitwarden.sh start
 _     _ _                         _
| |__ (_) |___      ____ _ _ __ __| | ___ _ __
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2018, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

Docker version 18.03.1-ce, build 9ee9f40
docker-compose version 1.21.2, build a133471

Traceback (most recent call last):
  File "/bin/docker-compose", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 71, in main
    command()
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 124, in perform_command
    project = project_from_options('.', options)
  File "/usr/lib/python2.7/site-packages/compose/cli/command.py", line 41, in project_from_options
    compatibility=options.get('--compatibility'),
  File "/usr/lib/python2.7/site-packages/compose/cli/command.py", line 121, in get_project
    host=host, environment=environment
  File "/usr/lib/python2.7/site-packages/compose/cli/command.py", line 92, in get_client
    environment=environment, tls_version=get_tls_version(environment)
  File "/usr/lib/python2.7/site-packages/compose/cli/docker_client.py", line 120, in docker_client
    client = APIClient(**kwargs)
  File "/usr/lib/python2.7/site-packages/docker/api/client.py", line 110, in __init__
    config_dict=self._general_configs
TypeError: load_config() got an unexpected keyword argument 'config_dict
```

Docker Version:

```
[root@centos-2gb-bitwarden bitwarden]# docker -v
Docker version 18.03.1-ce, build 9ee9f40
```

Docker-Compose Version:

```
[root@centos-2gb-bitwarden bitwarden]# docker-compose -v
docker-compose version 1.21.2, build a133471
```

Installed PIP packages:

```
oot@centos-2gb-bitwarden bitwarden]# pip list
Babel (0.9.6)
backports.ssl-match-hostname (3.5.0.1)
cached-property (1.4.2)
certifi (2018.4.16)
chardet (3.0.4)
cloud-init (0.7.9)
configobj (4.7.2)
decorator (3.4.0)
docker (3.3.0)
docker-compose (1.21.2)
docker-py (1.10.6)
docker-pycreds (0.2.3)
dockerpty (0.4.1)
docopt (0.6.2)
enum34 (1.1.6)
functools32 (3.2.3.post2)
idna (2.6)
iniparse (0.4)
ipaddress (1.0.22)
IPy (0.75)
Jinja2 (2.7.2)
jsonpatch (1.2)
jsonpointer (1.9)
jsonschema (2.6.0)
kitchen (1.1.1)
MarkupSafe (0.11)
perf (0.1)
pip (8.1.2)
policycoreutils-default-encoding (0.1)
prettytable (0.7.2)
pycurl (7.19.0)
pygobject (3.22.0)
pygpgme (0.3)
pyliblzma (0.5.3)
pyserial (2.6)
python-linux-procfs (0.4.9)
pyudev (0.15)
pyxattr (0.5.1)
PyYAML (3.10)
requests (2.18.4)
schedutils (0.4)
seobject (0.1)
sepolicy (1.1)
setuptools (0.9.8)
six (1.9.0)
slip (0.4.0)
slip.dbus (0.4.0)
texttable (0.9.1)
urlgrabber (3.10)
urllib3 (1.22)
websocket-client (0.47.0)
yum-metadata-parser (1.1.4)
You are using pip version 8.1.2, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

Any help would be appreciated. Thanks

**Comment by waza-ari** [comment]
Got it working using the comment by @igorescobar in this thread:

https://github.com/ansible/awx/issues/1197

Essentially:

```
pip uninstall docker-py --no-cache-dir
pip install docker==3.1.4
```
