### ISSUE TITLE
Update failed

### ISSUE THREAD

**Issue by jpaechnatz** [bitwarden/core#304]
Environment, x86_64, centos 7, 8GB RAM
bitwarden was running some time.

I tried to update my bitwarden installation.
./bitwarden.sh updateself 
worked without error

./bitwarden.sh update "finished" with that last lines:

...
Status: Image is up to date for bitwarden/setup:1.20.0

Migrating database.
Database is in script upgrade mode. Trying again (attempt #2)...
Migrating database.
Database is in script upgrade mode. Trying again (attempt #3)...
Migrating database.

Unhandled Exception: System.Data.SqlClient.SqlException: Login failed for user 'sa'. Reason: Server is in script upgrade mode. Only administrator can connect at this time.
   at Bit.Setup.Program.MigrateDatabase(Int32 attempt) in /Users/kyle/Projects/bitwarden/core/util/Setup/Program.cs:line 285
   at Bit.Setup.Program.MigrateDatabase(Int32 attempt) in /Users/kyle/Projects/bitwarden/core/util/Setup/Program.cs:line 281
   at Bit.Setup.Program.MigrateDatabase(Int32 attempt) in /Users/kyle/Projects/bitwarden/core/util/Setup/Program.cs:line 281
   at Bit.Setup.Program.Main(String[] args) in /Users/kyle/Projects/bitwarden/core/util/Setup/Program.cs:line 57

What could I do to get it back up and running???

**Comment by kspearrin** [comment]
Try running `./bitwarden.sh updatedb`

**Comment by jpaechnatz** [comment]
After running /bitwarden.sh updatedb and an additional update it worked. Thanks.

Solved.
