### ISSUE TITLE
Exception in API on authentication

### ISSUE THREAD

**Issue by maddinat0r** [bitwarden/core#306]
I'm getting an exception when using a custom HTTP port:
```
bitwarden-api      | info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
bitwarden-api      |       Request starting HTTP/1.0 GET http://<URL>/accounts/profile
bitwarden-api      | fail: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[3]
bitwarden-api      |       Exception occurred while processing message.
bitwarden-api      | System.InvalidOperationException: IDX10803: Unable to obtain configuration from: 'http://identity/.well-known/openid-configuration'. ---> System.IO.IOException: IDX10804: Unable to retrieve document from: 'http://identity/.well-known/openid-configuration'. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: Couldn't connect to server
bitwarden-api      |    at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
bitwarden-api      |    at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
bitwarden-api      |    --- End of inner exception stack trace ---
bitwarden-api      |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
bitwarden-api      |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
bitwarden-api      |    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
bitwarden-api      |    at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
bitwarden-api      | --- End of stack trace from previous location where exception was thrown ---
bitwarden-api      |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
bitwarden-api      |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
bitwarden-api      |    at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.<GetDocumentAsync>d__8.MoveNext()
bitwarden-api      |    --- End of inner exception stack trace ---
bitwarden-api      |    at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.<GetDocumentAsync>d__8.MoveNext()
bitwarden-api      | --- End of stack trace from previous location where exception was thrown ---
bitwarden-api      |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
bitwarden-api      |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
bitwarden-api      |    at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.<GetAsync>d__3.MoveNext()
bitwarden-api      | --- End of stack trace from previous location where exception was thrown ---
bitwarden-api      |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
bitwarden-api      |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
bitwarden-api      |    at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.<GetConfigurationAsync>d__24.MoveNext()
bitwarden-api      |    --- End of inner exception stack trace ---
bitwarden-api      |    at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.<GetConfigurationAsync>d__24.MoveNext()
bitwarden-api      | --- End of stack trace from previous location where exception was thrown ---
bitwarden-api      |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
bitwarden-api      |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
bitwarden-api      |    at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.<HandleAuthenticateAsync>d__6.MoveNext()
bitwarden-api      | fail: Microsoft.AspNetCore.Server.Kestrel[13]
bitwarden-api      |       Connection id "0HLEDIA9P1USC", Request id "0HLEDIA9P1USC:00000001": An unhandled exception was thrown by the application.
bitwarden-api      | System.InvalidOperationException: IDX10803: Unable to obtain configuration from: 'http://identity/.well-known/openid-configuration'. ---> System.IO.IOException: IDX10804: Unable to retrieve document from: 'http://identity/.well-known/openid-configuration'. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: Couldn't connect to server
bitwarden-api      |    at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
bitwarden-api      |    at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
bitwarden-api      |    --- End of inner exception stack trace ---
bitwarden-api      |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
bitwarden-api      |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
bitwarden-api      |    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
bitwarden-api      |    at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
bitwarden-api      | --- End of stack trace from previous location where exception was thrown ---
bitwarden-api      |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
bitwarden-api      |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
bitwarden-api      |    at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.<GetDocumentAsync>d__8.MoveNext()
bitwarden-api      |    --- End of inner exception stack trace ---
bitwarden-api      |    at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.<GetDocumentAsync>d__8.MoveNext()
bitwarden-api      | --- End of stack trace from previous location where exception was thrown ---
bitwarden-api      |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
bitwarden-api      |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
bitwarden-api      |    at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.<GetAsync>d__3.MoveNext()
bitwarden-api      | --- End of stack trace from previous location where exception was thrown ---
bitwarden-api      |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
bitwarden-api      |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
bitwarden-api      |    at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.<GetConfigurationAsync>d__24.MoveNext()
bitwarden-api      |    --- End of inner exception stack trace ---
bitwarden-api      |    at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.<GetConfigurationAsync>d__24.MoveNext()
bitwarden-api      | --- End of stack trace from previous location where exception was thrown ---
bitwarden-api      |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
bitwarden-api      |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
bitwarden-api      |    at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.<HandleAuthenticateAsync>d__6.MoveNext()
bitwarden-api      | --- End of stack trace from previous location where exception was thrown ---
bitwarden-api      |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
bitwarden-api      |    at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.<HandleAuthenticateAsync>d__6.MoveNext()
bitwarden-api      | --- End of stack trace from previous location where exception was thrown ---
bitwarden-api      |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
bitwarden-api      |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
bitwarden-api      |    at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.<AuthenticateAsync>d__47.MoveNext()
bitwarden-api      | --- End of stack trace from previous location where exception was thrown ---
bitwarden-api      |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
bitwarden-api      |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
bitwarden-api      |    at Microsoft.AspNetCore.Authentication.AuthenticationService.<AuthenticateAsync>d__10.MoveNext()
bitwarden-api      | --- End of stack trace from previous location where exception was thrown ---
bitwarden-api      |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
bitwarden-api      |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
bitwarden-api      |    at IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler.<HandleAuthenticateAsync>d__2.MoveNext()
bitwarden-api      | --- End of stack trace from previous location where exception was thrown ---
bitwarden-api      |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
bitwarden-api      |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
bitwarden-api      |    at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.<AuthenticateAsync>d__47.MoveNext()
bitwarden-api      | --- End of stack trace from previous location where exception was thrown ---
bitwarden-api      |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
bitwarden-api      |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
bitwarden-api      |    at Microsoft.AspNetCore.Authentication.AuthenticationService.<AuthenticateAsync>d__10.MoveNext()
bitwarden-api      | --- End of stack trace from previous location where exception was thrown ---
bitwarden-api      |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
bitwarden-api      |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
bitwarden-api      |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
bitwarden-api      | --- End of stack trace from previous location where exception was thrown ---
bitwarden-api      |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
bitwarden-api      |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
bitwarden-api      |    at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()
bitwarden-api      | --- End of stack trace from previous location where exception was thrown ---
bitwarden-api      |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
bitwarden-api      |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
bitwarden-api      |    at Bit.Core.Utilities.ServiceCollectionExtensions.<>c.<<UseDefaultMiddleware>b__9_0>d.MoveNext() in /Users/kyle/Projects/bitwarden/core/src/Core/Utilities/ServiceCollectionExtensions.cs:line 330
bitwarden-api      | --- End of stack trace from previous location where exception was thrown ---
bitwarden-api      |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
bitwarden-api      |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
bitwarden-api      |    at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
bitwarden-api      | --- End of stack trace from previous location where exception was thrown ---
bitwarden-api      |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
bitwarden-api      |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
bitwarden-api      |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
bitwarden-api      | info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
bitwarden-api      |       Request finished in 342.0904ms 500
```
It seems to access `http://identity/.well-known/openid-configuration`, but it should be `http://identity:8080/.well-known/openid-configuration` as `8080` is the HTTP port I'm using internally. Is there any way to configure this?

**Comment by kspearrin** [comment]
Are you using docker compose? These hostnames should all be part of the same network. The internal domains are configurable through the env files.

**Comment by maddinat0r** [comment]
Yes, I'm using a custom Docker compose setup. While doing a manual update, I forgot to update the `global.env` file, where all the internal domains were missing the corresponding port (it was the default `5000` port, not `8080`, a mistake on my side again). So yeah, I managed to resolve my issue. 
Thanks for your help!
