### ISSUE TITLE
Cannot send E-mails (admin and mail verification)

### ISSUE THREAD

**Issue by arnoldsuperstar** [bitwarden/core#311]
Hi,
I've installed Bitwarden on my own server following the documentation.

I've defined my SMTP setting as follows:

```
globalSettings__mail__replyToEmail=bitwarden@domain.be
globalSettings__mail__smtp__host=ssl0.ovh.net
globalSettings__mail__smtp__username=bitwarden@domain.be
globalSettings__mail__smtp__password=<the_password>
globalSettings__mail__smtp__ssl=true
globalSettings__mail__smtp__port=465
globalSettings__mail__smtp__useDefaultCredentials=false
```

However, both mails for admin connection and for E-mail verification fail to be sent.

When sending the admin mail, I get the following error in /logs/admin/Admin:

```
2018-06-14 12:22:07.965 +00:00 [Error] Error sending mail with primary service, using backup.
System.InvalidOperationException: Cannot find compilation library location for package 'Microsoft.Win32.Registry'
   at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths(ICompilationAssemblyResolver resolver, List`1 assemblies)
   at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at RazorLight.Compilation.DefaultMetadataReferenceManager.Resolve(Assembly assembly)
   at RazorLight.Compilation.RoslynCompilationService.EnsureOptions()
   at RazorLight.Compilation.RoslynCompilationService.get_ParseOptions()
   at RazorLight.Compilation.RoslynCompilationService.CreateCompilation(String compilationContent, String assemblyName)
   at RazorLight.Compilation.RoslynCompilationService.CompileAndEmit(GeneratedRazorTemplate razorTemplate)
   at RazorLight.TemplateFactoryProvider.CreateFactory(GeneratedRazorTemplate razorTemplate)
   at RazorLight.TemplateFactoryProvider.<CreateFactoryAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RazorLight.RazorLightEngine.<CompileTemplateAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RazorLight.RazorLightEngine.<CompileRenderAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Bit.Core.Services.RazorMailService.<SendPasswordlessSignInAsync>d__15.MoveNext() in /Users/kyle/Projects/bitwarden/core/src/Core/Services/Implementations/RazorMailService.cs:line 221
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Bit.Core.Services.BackupMailService.<SendPasswordlessSignInAsync>d__14.MoveNext() in /Users/kyle/Projects/bitwarden/core/src/Core/Services/Implementations/BackupMailService.cs:line 160
2018-06-14 12:27:08.108 +00:00 [Error] Mail send failed.
System.Net.Mail.SmtpException: Syntax error, command unrecognized. The server response was: 
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.End(IAsyncResult result)
   at System.Net.Mail.SmtpTransport.EndGetConnection(IAsyncResult result)
   at System.Net.Mail.SmtpClient.ConnectCallback(IAsyncResult result)

```
And in /log/api/Api when sending the E-mail verification message:

```
2018-06-14 12:12:11.975 +00:00 [Error] Mail send failed.
System.Net.Mail.SmtpException: Syntax error, command unrecognized. The server response was: 
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.End(IAsyncResult result)
   at System.Net.Mail.SmtpTransport.EndGetConnection(IAsyncResult result)
   at System.Net.Mail.SmtpClient.ConnectCallback(IAsyncResult result)

```

Note that the mail account does work properly.

How do I further investigate this? The error messages look truncated to me.

Thanks for your help!

**Comment by arnoldsuperstar** [comment]
Some additional info:
Docker version 17.05.0-ce, build 89658be
docker-compose version 1.21.2, build a133471
bitwarden 1.20.0

**Comment by kspearrin** [comment]
The first error is known and would not cause any issue with the email going out.

The second error from API is the real reason. This usually happens when your SMTP settings are not correct. Have you tested this independent of Bitwarden to confirm that they work? For example, many mail providers use port 587 for SSL.

**Comment by arnoldsuperstar** [comment]
@kspearrin Ok, definitely, there is something weird with SSL at my provider's side, which is OVH. Their doc: https://docs.ovh.com/fr/emails/generalites-sur-les-emails-mutualises/#rappel-des-parametres-imap-et-pop (in French only, sorry about that)

They expose port 587 without SSL and it works perfectly in this case. With SSL, I'm supposed to work with port 465. And in this case, I'm facing a time-out using Evolution with the same account.

In Evolution, I have to define the "Encryption method". If I choose "TLS", the server immediately rejects the message, and with "STARTTLS" I have the time-out. So I gonna ask OVH what's wrong with my settings.

But, in the case of Bitwarden, if I enable SSL with the parameter "globalSettings__mail__smtp__ssl", which encryption method will be used?

**Comment by kspearrin** [comment]
With `globalSettings__mail__smtp__ssl` set to true, you should be using TLS or SSL with your provider.

**Comment by kspearrin** [comment]
Closing this now since it's a config issue. Feel free to follow up with any other questions or info here still though.
