### ISSUE TITLE
HTTP 500 on /api/two-factor/yubikey for Yubico OTP keys "typed" in non-QWERTY layout

### ISSUE THREAD

**Issue by drdaeman** [bitwarden/core#318]
I've just noticed that trying to register Yubikey (using Yubico OTP method) in non-QWERTY layout makes server respond with an HTTP 500 error and UI shows "An unhandled server error has occurred."

An example request, with two already registered keys (where I've switched to QWERTY; asterisks are mine, don't want to unnecessarily expose key IDs in public) and one new key (actually the same as key1, but this happens regardless of this) when I've "forgot" to switch from Dvorak:

    POST /api/two-factor/yubikey
    {
        "key1": "cccccc******",
        "key2": "vv**********",
        "key3": "jjjjjj*************************************",
        "masterPasswordHash": "********",
        "nfc": false
    }

Results in the following response with HTTP 500 status code:

    {
        "Message":"An unhandled server error has occurred.",
        "ValidationErrors":null,
        "ExceptionMessage":null,
        "ExceptionStackTrace":null,
        "InnerExceptionMessage":null,
        "Object":"error"
    }

This does not happen if I provide long-enough invalid code like "abcdefghijklmnopqrstuvwxyz". In such case I get the correct HTTP 400 with `ValidationErrors` saying "Key3 is invalid." error response. Re-submitting the same token also makes server respond with HTTP 400. This is why I suspect this only happens with valid tokens - exactly once, because the second time replay protection would kick in and such key is rejected.

Of course, it would be best if non-QWERTY inputs would be recognized (some projects implement this with [a mapping table](https://github.com/firnsy/yubipam/blob/48859f5043a410e0adac17c24abb096b7f110521/src/utils/yk_chkpwd.c#L77), trying the original and a few remapped strings), but that would be a feature request. :) One way or another, I believe an unhanded exception is something worth reporting and investigating.

Sorry, I don't have enough ASP.NET experience (and spare time) to debug this myself. Just reporting the behavior I've seen on the website.

**Comment by FabioWidmer** [comment]
I am getting the same error. Hope this problem gets fixed soon.

**Comment by kspearrin** [comment]
For now you will have to temporarily switch to qwerty mode when using the YubiKey.

**Comment by FabioWidmer** [comment]
I did that but this doesn't work for me.

**Comment by labor4** [comment]
> For now you will have to temporarily switch to qwerty mode when using the YubiKey.

Do I understand correctly? Switching the keyboard layout?
Not working for me.

I think the issue might be even different. 
Playing out strings in a text editor from my Yubikey there seem not to be any Zs or Ys, so maybe they disabled those switching characters? If so the issue could be completely different.

Could somebody with a working setup test against this question?

**Comment by labor4** [comment]
For me this was solved like this.
Conditions:

- hosted it myself
- get API Key here https://upgrade.yubico.com/getapikey
- put credentials into file "global.override.env" under keys "globalSettings__yubico__clientId" and "globalSettings__yubico__key"
- restart bitwarden

...thereby giving your own server access to the official yubikey verification servers.

**Comment by joshuaavalon** [comment]
I have getting the following error, after I added yubico api key

> info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Route matched with {action = "PutYubiKey", controller = "TwoFactor"}. Executing action Bit.Api.Controllers.TwoFactorController.PutYubiKey (Api)
> info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
      Authorization was successful.
> info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method Bit.Api.Controllers.TwoFactorController.PutYubiKey (Api) with arguments (Bit.Core.Models.Api.UpdateTwoFactorYubicoOtpRequestModel) - Validation state: Valid
> fail: Bit.Api.Utilities.ExceptionHandlerFilterAttribute[0]
      The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at YubicoDotNetClient.YubicoClient..ctor(String clientId, String apiKey)
   at Bit.Core.Identity.YubicoOtpTokenProvider.ValidateAsync(String purpose, String token, UserManager1 manager, User user) in /home/appveyor/projects/core/src/Core/Identity/YubicoOtpTokenProvider.cs:line 69
   at Microsoft.AspNetCore.Identity.UserManager1.VerifyTwoFactorTokenAsync(TUser user, String tokenProvider, String token)
   at Bit.Api.Controllers.TwoFactorController.ValidateYubiKeyAsync(User user, String name, String value) in /home/appveyor/projects/core/src/Api/Controllers/TwoFactorController.cs:line 398
   at Bit.Api.Controllers.TwoFactorController.PutYubiKey(UpdateTwoFactorYubicoOtpRequestModel model) in /home/appveyor/projects/core/src/Api/Controllers/TwoFactorController.cs:line 124
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync()

**Comment by bradediger** [comment]
If you use mostly one non-QWERTY keyboard layout, the easiest solution may be just to reprogram your yubikey's scancodes with the new keymap using [ykpersonalize](https://developers.yubico.com/yubikey-personalization/Manuals/ykpersonalize.1.html).

For example, this worked to update a Yubikey 5 to us-dvorak:

```shell
ykpersonalize -S0c110b071c180d0a0619130f120e09378c918b879c988d8a8699938f928e89b7271e1f202122232425269e2b28
```

**Comment by piotrkochan** [comment]
Same for me
```
Linux 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64 GNU/Linux
```

**Comment by piotrkochan** [comment]
Sorry, actually I'm getting 500 on the register endpoint.

**Comment by rangzen** [comment]
> I am getting the same error. Hope this problem gets fixed soon.

Got the bug just now so it seems that "soon" is relative...

**Comment by rangzen** [comment]
@bitwarden-bot Please robot, don't close this one. The issue is still relevant.

**Comment by ifernandezdiaz** [comment]
Hi, @drdaeman and @rangzen! I tried to replicate this issue but with no luck. Any other information you can provide me will be appreciated!

**Comment by rangzen** [comment]
Hello @ifernandezdiaz, add the French language pack, by default in Azerty keymap, everything is fine. Add a keymap lik "bépo", change to this keymap, the login in Bitwarden is now impossible.

**Comment by CryptoSiD** [comment]
I'm having the same issue on the latest Bitwarden version (2022.8.1).

**Comment by Anthony-95** [comment]
Hello im facing a different error after resolving the first problem with the solution of @labor4 

I register my Yubico 5C NFC at https://upgrade.yubico.com/getapikey
I put the credentials into file "global.override.env"
I rebuild and restart bitwarden

When I try to add a new OTP Yubico key I got the 500 error. Here is api log:

2022-11-08 20:48:21.775 +00:00 [Error] Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Bit.Core.Identity.YubicoOtpTokenProvider.ValidateAsync(String purpose, String token, UserManager`1 manager, User user) in /home/runner/work/server/server/src/Core/Identity/YubicoOtpTokenProvider.cs:line 72
   at Microsoft.AspNetCore.Identity.UserManager`1.VerifyTwoFactorTokenAsync(TUser user, String tokenProvider, String token)
   at Bit.Api.Controllers.TwoFactorController.ValidateYubiKeyAsync(User user, String name, String value) in /home/runner/work/server/server/src/Api/Controllers/TwoFactorController.cs:line 447
   at Bit.Api.Controllers.TwoFactorController.PutYubiKey(UpdateTwoFactorYubicoOtpRequestModel model) in /home/runner/work/server/server/src/Api/Controllers/TwoFactorController.cs:line 125
   at lambda_method137(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

**Comment by closebot-bw** [comment]
⚠️ **Stale Issue Notice**

This issue has been automatically marked as stale due to inactivity. It will be closed in **2 weeks** (October 15, 2025) if no further activity occurs.

If this issue is still relevant and you would like to keep it open, please:
- Comment on this issue to show continued interest
- Provide any additional information or updates
- Confirm that the issue still exists in the latest version

Thank you for your contribution to this project! 🙏

**Comment by closebot-bw** [comment]
🔒 **Issue Closed Due to Inactivity**

This issue has been automatically closed due to lack of activity for an extended period. We periodically review and close inactive issues to help maintain our issue tracker and focus on current priorities.

**If this issue is still relevant:**
- Please create a new issue with updated information
- Include steps to reproduce the problem if it's a bug report
- Mention if this issue still occurs in the latest version

Thank you for your contribution to this project. Your feedback helps us improve! 🙏
