### ISSUE TITLE
Can't login - No route to host nginx error.log

### ISSUE THREAD

**Issue by alexhk** [bitwarden/core#343]
I am a licensed/paid user. 

Since the last update I can't access my self-hosted instance via the web. It shows a red box with:

An error has occurred.
An unexpected error has occurred.

It also seems the browser plugin can't connect to the server (no error, but it doesn't save new logins).

I am not sure which logs to check, but what I can find that stands out is this:

/bwdata/logs/nginx/error.log
```
2018/08/19 18:05:39 [error] 40#40: *6 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.0.1, server: myhost.domain.ch, request: "POST /identity/connect/token HTTP/2.0", upstream: "http://172.18.0.5:5000/connect/token", host: "myhost.domain.ch:8443"
```

Notes: 
- I replaced my domain with myhost.domain.ch, rest is as in the log file.
- I am indeed using port 8443 (self issued certificate).

Any ideas what I could try next?

I already tried restarting bitwarden, restarting the server, reinstalling the latest version using ./bitwarden.sh updateself and update.

'docker ps' shows the following:

```
CONTAINER ID        IMAGE                          COMMAND             CREATED             STATUS                            PORTS                                                    NAMES
94f63536aa84        bitwarden/icons:1.22.0         "/entrypoint.sh"    19 minutes ago      Restarting (139) 13 seconds ago                                                            bitwarden-icons
924bffe4540e        bitwarden/mssql:1.22.0         "/entrypoint.sh"    19 minutes ago      Up 19 minutes                     1433/tcp                                                 bitwarden-mssql
7a89450a7532        bitwarden/api:1.22.0           "/entrypoint.sh"    19 minutes ago      Restarting (139) 12 seconds ago                                                            bitwarden-api
468abdb0e027        bitwarden/nginx:1.22.0         "/entrypoint.sh"    19 minutes ago      Up 19 minutes                     0.0.0.0:8080->8080/tcp, 80/tcp, 0.0.0.0:8443->8443/tcp   bitwarden-nginx
42748ce256ff        bitwarden/identity:1.22.0      "/entrypoint.sh"    19 minutes ago      Restarting (139) 13 seconds ago                                                            bitwarden-identity
067b2257b5bd        bitwarden/attachments:1.22.0   "/entrypoint.sh"    19 minutes ago      Up 19 minutes                     5000/tcp                                                 bitwarden-attachments
08ee7ab869c8        bitwarden/admin:1.22.0         "/entrypoint.sh"    19 minutes ago      Restarting (139) 16 seconds ago                                                            bitwarden-admin
fec98e0e11da        bitwarden/web:2.1.1            "/entrypoint.sh"    19 minutes ago      Up 19 minutes                     5000/tcp                                                 bitwarden-web
```

-- // --

What's a bit annoying is that I had to find out by trying to login via the web. I saved a login via the Firefox plugin yesterday and noticed today that it apparently didn't save it. I then logged in again to that specific website and was asked again by Bitwarden if I want to store the login, hit yes, and again it wasn't saved. There was no error message that Bitwarden couldn't save it or not connect to the server... only now when I manually tried to login to the web interface to see what's up I found out. Maybe an error message could be added to the browser plugin if it can't connecte to the server... luckily I had to password created with Bitwarden so I could go thorugh the password generation history to get the password it didn't save.

**Comment by kspearrin** [comment]
Stop everything and then try running ‘docker-compose up’ from the ‘bwdata/docker’ directory to see why the containers are failing to start.

**Comment by alexhk** [comment]
Seems here is where it fails first:

```
^[[33;1mbitwarden-admin |^[[0m
^[[33;1mbitwarden-admin |^[[0m Unhandled Exception: System.ArgumentOutOfRangeException: Version's parameters must be greater than or equal to zero.
^[[33;1mbitwarden-admin |^[[0m Parameter name: revision
^[[33;1mbitwarden-admin |^[[0m    at System.Version..ctor(Int32 major, Int32 minor, Int32 build, Int32 revision)
^[[33;1mbitwarden-admin |^[[0m    at System.Environment.<>c.<.cctor>b__79_0()
^[[33;1mbitwarden-admin |^[[0m    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
^[[33;1mbitwarden-admin |^[[0m    at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
^[[33;1mbitwarden-admin |^[[0m    at System.Lazy`1.CreateValue()
^[[33;1mbitwarden-admin |^[[0m    at System.Environment.get_OSVersion()
^[[33;1mbitwarden-admin |^[[0m    at Microsoft.AspNetCore.Hosting.WebHostBuilderIISExtensions.UseIISIntegration(IWebHostBuilder hostBuilder)
^[[33;1mbitwarden-admin |^[[0m    at Microsoft.AspNetCore.WebHost.CreateDefaultBuilder(String[] args)
^[[33;1mbitwarden-admin |^[[0m    at Bit.Admin.Program.Main(String[] args) in /Users/kyle/Projects/bitwarden/core/src/Admin/Program.cs:line 10
```

Here is the full output:
https://pastebin.com/X5QAugC9

**Comment by kspearrin** [comment]
According to the log it's trying to use iis integration, which is a Windows thing. That doesn't sound right at all. What kind of OS is this being run on?

**Comment by alexhk** [comment]
It's running on Ubuntu 16.04.5 LTS. I had it since version 1.15 on that machine. I believe on the last update I went from 1.20 to 1.22 directly, but would have to check to make sure it's true.

Could I downgrade to the last version I had?
Is reinstalling and using data/settings from backup an option?
Any other suggestion at this point?

**Comment by kspearrin** [comment]
You could downgrade, but you would also have to revert the database migrations as well, which could only be done from a backup of `bwdata/mssql`. Do you have a database backup?

**Comment by alexhk** [comment]
I do have the automated nightly backups created by Bitwarden and I have an off-site rsync of the complete bwdata directory.

Are you investigating what could have caused the last version to suddenly try to access IIS? Not sure if I should downgrade or wait for you to figure out what went wrong. I assume I am the only one with this problem at this point :/

Possibly running a local On-Premise Bitwarden server on my local Windows machine for the time being (until we know what caused it) is a solution, before moving back to the Ubuntu server.

Another solution would be to move the data to vauld.bitwarden.com, but this would not be easy without access to the web UI to export the data I assume.

**Comment by kspearrin** [comment]
Yes, I am still interested in trying to figure out what is going on here, but no one else has reported this issue yet, so it seems specific to your environment for whatever reason. Could you try running a fresh new installation on the same machine and see if the problem occurs with it too?

**Comment by alexhk** [comment]
My schedule just cleared up so I will give it a try.

How do I remove Bitwarden for a clean install? Or did you just mean install it over the current installation?

**Comment by kspearrin** [comment]
you don't need to remove the current installation. just stop it with `./bitwarden.sh stop`. 

then make a new directory and do a new clean install there.

**Comment by alexhk** [comment]
The new install stops with "Unable to validate installation id. Problem contacting Bitwarden server."

I can manually access https://api.bitwarden.com/installations/INSTALLATION_ID just fine from that machine.

**Comment by kspearrin** [comment]
But can you access it from within a docker container? Is there some firewall on your docker containers or something? Does outbound traffic require a CA cert?

**Comment by alexhk** [comment]
Yes, absolutely. I run wget https://api.bitwarden.com/installations/INSTALLATION_ID just fine and I don't have a firewall for outbound connections etc.

Something either changed with the latest Bitwarden update or with the standard docker repository coming with Ubuntu. I assume it was Bitwarden, as it all stopped working with the last update.

**Comment by alexhk** [comment]
I tried installing the new version which you released in the meantime, same problem.
I simply don't see a reason why the installer can't contact the Bitwarden server, I tried everything from accessing it from within or outside using wget or curl on https:// and there is no problem as far as I can tell. I also tried sniffing the traffic from the docker container but it's not something I have done before. I won't try getting this to work any longer.

I tried installing on a Digital Ocean droplet, but during the install some http request took too long and again I was not successful (see below code for reference).

Anyway, I was probably just lucky with my self-hosted install so far and will be moving away from it.

Now, I exported my data from the web plugin recently as Bitwarden CSV. I imported this to vault.bitwarden.com and it showed up without folders?! I then deleted all the records manually, created a single folder ("Shopping"), imported the same file again, and  voile now all the folders where here. Not sure if my creating of a single folder helped or the first time was just unlucky.

Anyhow, I now have my logins at vault.bitwarden.com but I don't have my CARD data. I checked with the web plugin export and another test export on another system/account, it seems no matter using the Firefox plugin or the Bitwarden Windows executable, it does indeed not export card data. Hmm. Rather disappointing the complete experience.

I'd love to go back to the previous version (1.20 if I am not wrong, but I don't know how to confirm that) - I have all the backups including the nightly ones created by Bitwarden and a manual rsync of the complete folder before the upgrade. But I am simply not sure how to go back (how to get the old version?) and if it's worth it.

It all worked fine since last November, but now since end of July I am truly stuck with my Bitwarden install and my family is using the plugin/apps without server at the moment. I already had to save a few passwords in another place since the drama started...

For reference, here's what I had from within the Digital Ocean droplet:

```Creating bitwarden-nginx         ... 
Creating bitwarden-api           ... 
ERROR: for bitwarden-notifications  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
ERROR: for bitwarden-nginx  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
ERROR: for bitwarden-api  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
ERROR: for notifications  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
ERROR: for nginx  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
ERROR: for api  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
root@bw-ubuntu:~# ```

**Comment by kspearrin** [comment]
The errors you are getting in DO looks like it is related to this issue: https://github.com/docker/compose/issues/4486

**Comment by alexhk** [comment]
I am still trying to recover from backup :/

I have installed version 1.20 and it seems to install fine (to refresh your memory: when I tried 1.22 I wants to use windows IIS on my Ubuntu Linux and later versions won't connect to the Bitwarden licensing server - 1.20 had non of these problems and my backups are from this version).

But restoring from SQL doens't seem to do anything though. My login works, but no data shows up on the web vault.

NB: In my original install I had an organization ("domain.com") and premium and family license. These are no longer on the server and apparently won't work, since I moved to vault.bitwarden.com in the meantime, away from the self-hosted installation. Not sure if this missing licensing is related to the data not showing up.

Here's what I do:

```
DROP DATABASE vault;

CREATE DATABASE vault;

ALTER DATABASE vault

SET SINGLE_USER

WITH ROLLBACK IMMEDIATE

RESTORE DATABASE vault FROM DISK = '/vault_FULL_20180815_235901.BAK' WITH REPLACE;

All good and no errors.

./bitwarden.sh updatedb

```

Restarting Bitwarden doesn't make a difference.

I could restore MY data via export in the browser extension that still had a local copy. However, as mentioned elsewhere it doesn't export card data and collections, so I manually copy and pasted the missing data. Getting the json with Bitwarden CLI as a workaround is no option without a working server.

I cannot get OTHER users data because they don't have a local copy in their web extension (ie. mobile only users) to export and copy&paste from.

What I wanted to do was to get the 1.20 server running with the old SQL backup, then have the users do exports via web extensions or I do it with the CLI/json...

**Comment by kspearrin** [comment]
I am not sure why you would be able to successfully restore a database but them not see your organization's data. Even if your license was not provided yet, you would still see the deactivated organizations listed under the owber's user account.

You could install 1.20 if that's what you want to do. Just edit the ./bitwarden.sh script to use those versions instead of what is set by default there. Or just user docker-compose manually. The web vault would be a different version though so you'll need to look at the release logs of docker tag logs to see what web vault version was matched with 1.20 on the server.
