### ISSUE TITLE
Self Hosted - Unexpected error

### ISSUE THREAD

**Issue by cloudbluedigital** [bitwarden/core#345]
Hi guys,

So I am trying to install bitwarden on my server, installation itself went quite well. I can go to the url, register and login. But that's about it. I cannot add new items, I can't send a verification email despite the config being used in my other apps. I have installed it like this

```
arthur@Katon:/var/www/data$ sudo ./bitwarden.sh install
 _     _ _                         _
| |__ (_) |___      ____ _ _ __ __| | ___ _ __
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2018, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

Docker version 18.06.0-ce, build 0ffa825
docker-compose version 1.22.0, build f46880fe

(!) Enter the domain name for your Bitwarden instance (ex. bitwarden.company.com): bitwarden.cloudbluedigital.co.uk

(!) Do you want to use Let's Encrypt to generate a free SSL certificate? (y/n): n

1.22.0: Pulling from bitwarden/setup
Digest: sha256:e3c4906745a744c19f0ae01aab833b7e66a485fdf06a6e22f900d2c4dae4da38
Status: Image is up to date for bitwarden/setup:1.22.0

(!) Enter your installation id (get at https://bitwarden.com/host): id

(!) Enter your installation key: key

(!) Do you have a SSL certificate to use? (y/n): n

(!) Do you want to generate a self-signed SSL certificate? (y/n): y

Generating self signed SSL certificate.
Generating a 4096 bit RSA private key
.................++
....................++
writing new private key to '/bitwarden/ssl/self/bitwarden.cloudbluedigital.co.uk/private.key'
-----
Generating key for IdentityServer.
Generating a 4096 bit RSA private key
......................................................................................++
.................................................................................................................++
writing new private key to 'identity.key'
-----

!!!!!!!!!! WARNING !!!!!!!!!!
You are using an untrusted SSL certificate. This certificate will not be
trusted by Bitwarden client applications. You must add this certificate to
the trusted store on each device or else you will receive errors when trying
to connect to your installation.

(!) Do you want to use the default ports for HTTP (80) and HTTPS (443)? (y/n): n

(!) HTTPS port: 8443

(!) Is your installation behind a reverse proxy? (y/n): y

(!) Do you use the default HTTPS port (443) on your reverse proxy? (y/n): y

(!) Do you want to use push notifications? (y/n): y

Building nginx config.
Building docker environment files.
Building docker environment override files.
Building FIDO U2F app id.
Building docker-compose.yml.

Setup complete
```

while my reverse proxy nginx looks like:

```
server {
        server_name bitwarden.cloudbluedigital.co.uk;

        location / {

                proxy_pass https://localhost:8443;
  proxy_redirect off;
  proxy_set_header Host $http_host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;
  proxy_set_header X-Forwarded-Protocol $scheme;
  proxy_set_header X-Url-Scheme $scheme;
        }

        location /stub_status {
                stub_status;
                # Security: Only allow access from the IP below.
                allow 127.0.0.1;
                # Deny anyone else
                #deny all;
        }

    listen 80;
    listen 443 ssl http2; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/bitwarden.cloudbluedigital.co.uk/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/bitwarden.cloudbluedigital.co.uk/privkey.pem; # managed by Certbot
    include snippets/ssl.conf;

}
```

In terms of logs:
in admin:

```
2018-08-22 09:06:21.991 +00:00 [Error] An exception was thrown while deserializing the token.
Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted. ---> System.Security.Cryptography.CryptographicException: The key {121b8f27-4bca-47a3-80ae-ba36900828f5} was not found in the key ring.
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)
```

don't know if it's related but apart from that I can't see any errors unless there is a place where I haven't searched. if you need more details please let me know

if I go to `/admin` it loads fine but for example `/api` redirects me to `https://bitwarden.cloudbluedigital.co.uk:8443/api/` which fails to load

**Comment by kspearrin** [comment]
For whatever reason the API endpoint isn't accessible. How you were able to register without that working, I don't know. What is the status of `docker ps`?

**Comment by cloudbluedigital** [comment]
hi @kspearrin 
here's the output:
```
CONTAINER ID        IMAGE                          COMMAND             CREATED             STATUS              PORTS                            NAMES
baec84338319        bitwarden/identity:1.22.0      "/entrypoint.sh"    6 hours ago         Up 3 hours          5000/tcp                         bitwarden-identity
a223fab3e7e4        bitwarden/web:2.1.1            "/entrypoint.sh"    6 hours ago         Up 3 hours          5000/tcp                         bitwarden-web
4a689edae10c        bitwarden/admin:1.22.0         "/entrypoint.sh"    6 hours ago         Up 3 hours          5000/tcp                         bitwarden-admin
ca6a01a1c614        bitwarden/api:1.22.0           "/entrypoint.sh"    6 hours ago         Up 3 hours          5000/tcp                         bitwarden-api
ff9a34b0419a        bitwarden/mssql:1.22.0         "/entrypoint.sh"    6 hours ago         Up 3 hours          1433/tcp                         bitwarden-mssql
0f728102e87d        bitwarden/icons:1.22.0         "/entrypoint.sh"    6 hours ago         Up 3 hours          5000/tcp                         bitwarden-icons
19a03031aa13        bitwarden/attachments:1.22.0   "/entrypoint.sh"    6 hours ago         Up 3 hours          5000/tcp                         bitwarden-attachments
498f1c640ea7        bitwarden/nginx:1.22.0         "/entrypoint.sh"    6 hours ago         Up 3 hours          80/tcp, 0.0.0.0:8443->8443/tcp   bitwarden-nginx
```

also I have forgotten trailling slash in url for api so if i do https://bitwarden.cloudbluedigital.co.uk/api/ I get 404 instead and not being redirected to :8443

**Comment by kspearrin** [comment]
everything seems to be running fine. what does the developer tools network tab show when you try to add/edit an item in the web vault?

**Comment by cloudbluedigital** [comment]
I get:
```
400 Bad Request
Request Header Or Cookie Too Large
nginx/1.14.0 (Ubuntu)
```

**Comment by cloudbluedigital** [comment]
increasing `large_client_header_buffers` in nginx config seems to solve this issue, don't know why that occurs really
