### ISSUE TITLE
SMTP - GSSAPI operation failed with error - An invalid status code was supplied (Cannot find KDC for realm "...")

### ISSUE THREAD

**Issue by itadakimas** [bitwarden/core#355]
Hi there !

I've set up Bitwarden using Docker, and when I try to configure email two-way authentication, I get the following error :
```
bitwarden-api    | fail: Bit.Core.Services.SmtpMailDeliveryService[0]
bitwarden-api    |       Mail send failed.
bitwarden-api    | System.Net.Mail.SmtpException: Failure sending mail. ---> System.ComponentModel.Win32Exception: GSSAPI operation failed with error - An invalid status code was supplied (Cannot find KDC for realm "mydomain.tld").
bitwarden-api    |    at System.Net.Security.NegotiateStreamPal.AcquireCredentialsHandle(String package, Boolean isServer, NetworkCredential credential)
bitwarden-api    |    at System.Net.NTAuthentication.Initialize(Boolean isServer, String package, NetworkCredential credential, String spn, ContextFlagsPal requestedContextFlags, ChannelBinding channelBinding)
bitwarden-api    |    at System.Net.Mail.SmtpNegotiateAuthenticationModule.Authenticate(String challenge, NetworkCredential credential, Object sessionCookie, String spn, ChannelBinding channelBindingToken)
bitwarden-api    |    at System.Net.Mail.SmtpConnection.SetContextAndTryAuthenticate(ISmtpAuthenticationModule module, NetworkCredential credential, ContextAwareResult context)
bitwarden-api    |    at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.Authenticate()
bitwarden-api    |    at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.SendEHelloCallback(IAsyncResult result)
bitwarden-api    | --- End of stack trace from previous location where exception was thrown ---
bitwarden-api    |    at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.End(IAsyncResult result)
bitwarden-api    |    at System.Net.Mail.SmtpTransport.EndGetConnection(IAsyncResult result)
bitwarden-api    |    at System.Net.Mail.SmtpClient.ConnectCallback(IAsyncResult result)
bitwarden-api    |    --- End of inner exception stack trace ---

```
Any idea why this issue occurs ?

Regards

**Comment by kspearrin** [comment]
Seems related: https://github.com/dotnet/corefx/issues/29087 ?

**Comment by itadakimas** [comment]
Hi @kspearrin ! It seems related indeed.

My email client is using LOGIN authentication type. Do you think this issue is due to an incorrect authentication type (i.e. GSSAPI) ?

**Comment by kspearrin** [comment]
Perhaps. There is another variable you can set to change the auth type of you want:

```
globalSettings__mail__smtp__authType=SOMETHING
```

**Comment by itadakimas** [comment]
hmmm, I'll give it a try tonight. I haven't seen this variable in the documentation though. I couldn't find an issue on the help website repo for this. Would you like me to create a pull request ?

**Comment by kspearrin** [comment]
It's an undocumented property for now. It was recently added to help another user that needed it for an exchange server.

**Comment by itadakimas** [comment]
Thanks ! It worked !

Here is my configuration for an Exchange server :

```
globalSettings__mail__replyToEmail=name@domain.tld
globalSettings__mail__smtp__host=my.smtp.host.tld
globalSettings__mail__smtp__username=name@domain.tld
globalSettings__mail__smtp__password=password
globalSettings__mail__smtp__ssl=true
globalSettings__mail__smtp__port=587
globalSettings__mail__smtp__useDefaultCredentials=false
globalSettings__mail__smtp__authType=LOGIN
```
This should definitely be documented for those who get the same problem.

**Comment by abctaylor** [comment]
@LeKangouroo what do your receive connectors look like in Exchange? Mine:

```
Get-ReceiveConnector | where Identity -like *Authenticated*

Identity                                                 Bindings                                        Enabled
--------                                                 --------                                        -------
EXCHMBX1-LON\Authenticated Relay (authmx.core.domain.net) {10.2.10.15:587, 10.2.10.15:465, 10.2.10.15:25} True
EXCHMBX2-LON\Authenticated Relay (authmx.core.domain.net) {10.2.10.25:587, 10.2.10.25:465, 10.2.10.25:25} True
```

**Comment by LeKangouroo** [comment]
> 

I don't have access to the Exchange server. The maintenance is handled by the hosting provider.
