### ISSUE TITLE
Yubi key 2FA setup fails with server error

### ISSUE THREAD

**Issue by bkraul** [bitwarden/core#360]
When attempting to set up 2FA with Yubikey authentication, we are getting a notification with:
Server error occured.

The log shows:
```
fail: Bit.Api.Utilities.ExceptionHandlerFilterAttribute[0]
      The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at YubicoDotNetClient.YubicoClient..ctor(String clientId, String apiKey)
   at Bit.Core.Identity.YubicoOtpTokenProvider.ValidateAsync(String purpose, String token, UserManager`1 manager, User user) in /home/bitwarden/Projects/bitwarden/core/src/Core/Identity/YubicoOtpTokenProvider.cs:line 69
   at Microsoft.AspNetCore.Identity.UserManager`1.VerifyTwoFactorTokenAsync(TUser user, String tokenProvider, String token)
   at Bit.Api.Controllers.TwoFactorController.ValidateYubiKeyAsync(User user, String name, String value) in /home/bitwarden/Projects/bitwarden/core/src/Api/Controllers/TwoFactorController.cs:line 360
   at Bit.Api.Controllers.TwoFactorController.PutYubiKey(UpdateTwoFactorYubicoOtpRequestModel model) in /home/bitwarden/Projects/bitwarden/core/src/Api/Controllers/TwoFactorController.cs:line 121
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync()
```

I am not sure if it is related to #318 .
Any ideas?

**Comment by bkraul** [comment]
We did after looking at a Reddit post suggesting this. Changed on global.override.env and restarted the server. Problem still happened. However we tried several generated keys, and on about the 10th one it worked. We were able to log in to the web vault using the Yubikey.

However, something we are finding is that the OSX app does not prompt for Yubikey. There is a link in the app about 2FA that directs to the app. Is this by design, and the OSX App does not support Yubikey?

**Comment by kspearrin** [comment]
All apps support YubiKey. Are you logging in or only unlocking the app? 2FA only happens on unlock.

**Comment by bkraul** [comment]
Tried both (log in, lock, try to unlock). It only prompts for the master password, and after that it logs right in. We were thinking it was a refresh problem but we have quit the application, restarted the machine, and the same behavior persists.

**Comment by kspearrin** [comment]
Did you previous select to "remember me" on 2FA or something? Try deauthorizing sessions from web vault.

**Comment by bkraul** [comment]
There is no option to remember on the app's login screen, however it seems it does by default. We did log out completely from the app and tried and then the Yubikey prompt appeared. We also saw a settings under Lock Options, was set by default to Restart, we have now set it to 5 minutes, to test if the Yubikey will come up.

**Comment by kspearrin** [comment]
![image](https://user-images.githubusercontent.com/1190944/45964147-f5b3eb00-bff2-11e8-834b-51b4ae999a8a.png)

It is not checked by default

**Comment by bkraul** [comment]
We did see that one, which we expressly did not check. I was meaning here:

![image](https://user-images.githubusercontent.com/14616851/45964398-46bfe100-bfeb-11e8-8681-5fd7234292aa.png)

**Comment by bkraul** [comment]
@kspearrin We tried several times and found that the only way to get the Yubikey 2FA prompt to come on in the app is by logging out completely. Locking the vault and trying to unlock only asks for master password. We deauthorized all authenticated sessions, but after the first login with the Yubikey, it still would not prompt again, no matter if we restarted the machine (as long as we did not log out in the app). Setting the lock limit to 5 minutes also did not seem to work.

We have not tried this with the Windows app yet, but will as soon as we get another YubiKey.

**Comment by kspearrin** [comment]
Yes, this is the expected behavior for how 2FA works. Only on logging in. Not unlocking.

**Comment by bkraul** [comment]
I got you. I guess I should have read your previous reply better: "2FA only happens on login.". Is there a technical limitation for this? Seems to us it would be beneficial to have the option to require 2FA on unlock as well, due to potential physical access to the client.

**Comment by karrth** [comment]
In my case, I was able to resolve the "input is not a valid Base-64 string" error when adding a new yubikey by exposing port 80 for the bitwarden-nginx container on the docker host.  I had previously neglected to expose it, guessing I would not try to browse there.
